// Generated by resolved Action/Transition predicate/effect translation.
// Canonical typing/membership/source inputs and full lifecycle admission are handwritten dependencies.
pub(super) struct Inputs<'a> {pub composite:bool,pub structure:bool,pub data:bool,pub owner_kind:&'a str,pub owner_class:bool,pub owner_structure:bool,pub portion:&'a str,pub source_state:bool,pub entry_exit:bool}
impl Inputs<'_> {fn owner_is(&self,kind:&str)->bool {super::metaclass_conforms(self.owner_kind,kind)}}
pub(super) fn supports(kind:&str)->bool {matches!(kind,"ActionUsage"|"TransitionUsage")}
#[allow(unused_parens)]
pub(super) fn names(kind:&str,c:&Inputs<'_>)->Option<Vec<&'static str>> {let mut roles=Vec::new();match kind {
"ActionUsage" => {
    roles.push("base");
    if c.data {
        roles.push("dataValue");
    }
    if c.structure {
        roles.push(if c.composite && (c.owner_is("Structure") || (c.owner_is("Feature") && c.owner_structure)) { "subobject" } else { "object" });
    } else {
        if ((c.composite && (c.owner_is("Class") || (c.owner_is("Feature") && c.owner_class))) || (c.composite && c.owner_is("OccurrenceUsage"))) && (!((c.composite && (!c.entry_exit)) && (c.owner_is("ActionDefinition") || c.owner_is("ActionUsage")))) {
            roles.push("suboccurrence");
        }
    }
    if c.portion == "snapshot" {
        roles.push("snapshot");
    } else {
        if c.portion == "timeslice" {
            roles.push("timeslice");
        }
    }
    if (if (c.composite && (!c.entry_exit)) && (c.owner_is("ActionDefinition") || c.owner_is("ActionUsage")) { "subaction" } else { (if c.composite && (c.owner_is("PartDefinition") || c.owner_is("PartUsage")) { "ownedAction" } else { "" }) }) != "" {
        roles.push((if (c.composite && (!c.entry_exit)) && (c.owner_is("ActionDefinition") || c.owner_is("ActionUsage")) { "subaction" } else { (if c.composite && (c.owner_is("PartDefinition") || c.owner_is("PartUsage")) { "ownedAction" } else { "" }) }));
    }
    if c.composite && (c.owner_is("Structure") || (c.owner_is("Feature") && c.owner_structure)) {
        roles.push("ownedPerformance");
    } else {
        if (c.owner_is("Behavior") || c.owner_is("Step")) && c.composite {
            roles.push("subperformance");
        } else {
            if c.owner_is("Behavior") || c.owner_is("Step") {
                roles.push("enclosedPerformance");
            }
        }
    }
},
"TransitionUsage" => {
    roles.push(if (c.composite && (c.owner_is("StateDefinition") || c.owner_is("StateUsage"))) && c.source_state { "stateTransition" } else { if (c.composite && (c.owner_is("ActionDefinition") || c.owner_is("ActionUsage"))) && (!c.source_state) { "actionTransition" } else { "base" } });
    if c.data {
        roles.push("dataValue");
    }
    if c.structure {
        roles.push(if c.composite && (c.owner_is("Structure") || (c.owner_is("Feature") && c.owner_structure)) { "subobject" } else { "object" });
    } else {
        if ((c.composite && (c.owner_is("Class") || (c.owner_is("Feature") && c.owner_class))) || (c.composite && c.owner_is("OccurrenceUsage"))) && (!((c.composite && (!c.entry_exit)) && (c.owner_is("ActionDefinition") || c.owner_is("ActionUsage")))) {
            roles.push("suboccurrence");
        }
    }
    if c.portion == "snapshot" {
        roles.push("snapshot");
    } else {
        if c.portion == "timeslice" {
            roles.push("timeslice");
        }
    }
    if (if (c.composite && (!c.entry_exit)) && (c.owner_is("ActionDefinition") || c.owner_is("ActionUsage")) { "subaction" } else { (if c.composite && (c.owner_is("PartDefinition") || c.owner_is("PartUsage")) { "ownedAction" } else { "" }) }) != "" {
        roles.push((if (c.composite && (!c.entry_exit)) && (c.owner_is("ActionDefinition") || c.owner_is("ActionUsage")) { "subaction" } else { (if c.composite && (c.owner_is("PartDefinition") || c.owner_is("PartUsage")) { "ownedAction" } else { "" }) }));
    }
    if c.composite && (c.owner_is("Structure") || (c.owner_is("Feature") && c.owner_structure)) {
        roles.push("ownedPerformance");
    } else {
        if (c.owner_is("Behavior") || c.owner_is("Step")) && c.composite {
            roles.push("subperformance");
        } else {
            if c.owner_is("Behavior") || c.owner_is("Step") {
                roles.push("enclosedPerformance");
            }
        }
    }
},
_=>return None,}
let mut result=Vec::new();for role in roles {let name=match (kind,role) {
("ActionUsage","base")=>"Actions::actions",
("ActionUsage","dataValue")=>"Base::dataValues",
("ActionUsage","enclosedPerformance")=>"Performances::Performance::enclosedPerformances",
("ActionUsage","object")=>"Objects::objects",
("ActionUsage","ownedAction")=>"Parts::Part::ownedActions",
("ActionUsage","ownedPerformance")=>"Objects::Object::ownedPerformances",
("ActionUsage","snapshot")=>"Occurrences::Occurrence::snapshots",
("ActionUsage","subaction")=>"Actions::Action::subactions",
("ActionUsage","subobject")=>"Objects::Object::subobjects",
("ActionUsage","suboccurrence")=>"Occurrences::Occurrence::suboccurrences",
("ActionUsage","subperformance")=>"Performances::Performance::subperformances",
("ActionUsage","timeslice")=>"Occurrences::Occurrence::timeSlices",
("TransitionUsage","actionTransition")=>"Actions::Action::decisionTransitions",
("TransitionUsage","base")=>"Actions::transitionActions",
("TransitionUsage","dataValue")=>"Base::dataValues",
("TransitionUsage","enclosedPerformance")=>"Performances::Performance::enclosedPerformances",
("TransitionUsage","object")=>"Objects::objects",
("TransitionUsage","ownedAction")=>"Parts::Part::ownedActions",
("TransitionUsage","ownedPerformance")=>"Objects::Object::ownedPerformances",
("TransitionUsage","snapshot")=>"Occurrences::Occurrence::snapshots",
("TransitionUsage","stateTransition")=>"States::StateAction::stateTransitions",
("TransitionUsage","subaction")=>"Actions::Action::subactions",
("TransitionUsage","subobject")=>"Objects::Object::subobjects",
("TransitionUsage","suboccurrence")=>"Occurrences::Occurrence::suboccurrences",
("TransitionUsage","subperformance")=>"Performances::Performance::subperformances",
("TransitionUsage","timeslice")=>"Occurrences::Occurrence::timeSlices",
_=>return None,};if !result.contains(&name) {result.push(name);}}Some(result)}
