// Generated by tools/export_pilot_connector_defaults.py; do not edit.
// Verified Connector and BindingConnector maps. Native dependencies remain explicit.
pub(super) fn connector_default_name(owned_ends: usize, structure: bool) -> &'static str {
    match (owned_ends == 2, structure) {
        (false, false) => "Links::links",
        (true, false) => "Links::binaryLinks",
        (false, true) => "Objects::linkObjects",
        (true, true) => "Objects::binaryLinkObjects",
    }
}
pub(super) fn supports(kind: &str) -> bool { matches!(kind, "Connector" | "BindingConnector") }
// Resolved inherited Feature typing dispatch; native algorithm remains shared.
pub(super) fn typing_supported(kind: &str) -> bool { matches!(kind, "BindingConnector" | "Connector") }
pub(super) fn default_for(kind: &str, owned_ends: usize, structure: bool) -> Option<&'static str> {
    if kind == "Connector" { return Some(connector_default_name(owned_ends, structure)); }
    if kind != "BindingConnector" { return None; }
    Some(match (owned_ends == 2, structure) {
        (false, false) => "Links::links",
        (true, false) => "Links::selfLinks",
        (false, true) => "Objects::linkObjects",
        (true, true) => "Links::selfLinks",
    })
}
