// Generated by tools/export_pilot_default_generals.py; do not edit.
pub(super) const DEFAULT_GENERALS: &[(&str, &str, &str)] = &[
    ("Type", "Base::Anything", "Specialization"),
    ("Classifier", "Base::Anything", "Subclassification"),
    ("Class", "Occurrences::Occurrence", "Subclassification"),
    ("DataType", "Base::DataValue", "Subclassification"),
    ("Structure", "Objects::Object", "Subclassification"),
    ("AttributeDefinition", "Base::DataValue", "Subclassification"),
    ("Behavior", "Performances::Performance", "Subclassification"),
    ("ConjugatedPortDefinition", "Ports::Port", "Subclassification"),
    ("Definition", "Base::Anything", "Subclassification"),
    ("EnumerationDefinition", "Base::DataValue", "Subclassification"),
    ("Function", "Performances::Evaluation", "Subclassification"),
    ("Metaclass", "Metaobjects::Metaobject", "Subclassification"),
    ("PortDefinition", "Ports::Port", "Subclassification"),
    ("Predicate", "Performances::BooleanEvaluation", "Subclassification"),
];
