// Generated by tools/generate_ecore_ownership.py; do not edit.
// Resolved EMF input digest: 7c82a48bf659e2225e0d75515938150c021b27cd9700c7e4e616aa7805603a70
// Resolved Xtext input digest: 1ac1fc7fed307e8cf9d08427b8444395d203ef94861da8c7cc3077473a312d87
// Only ordered unique containment lists with optional scalar opposites are admitted.
use super::ecore_ownership::OwnershipContract;

pub(super) const OWNED_RELATIONSHIPS: OwnershipContract = OwnershipContract {
    owner_kind: "Element", child_kind: "Relationship",
    field: "owned_relationship", inverse: "owning_related_element",
};

pub(super) const OWNED_ELEMENTS: OwnershipContract = OwnershipContract {
    owner_kind: "Relationship", child_kind: "Element",
    field: "owned_related_element", inverse: "owning_relationship",
};

pub(super) const LEGACY_VERIFY_USAGE_METACLASS: &str = "RequirementUsage";
