// Generated by tools/generate_expression_context_defaults.py; do not edit.
pub(super) fn names(kind: &str, base: &'static str, composite: bool, structure_owned: bool, behavior_owned: bool) -> Option<Vec<&'static str>> {
    let mut names = vec![base];
    match kind {
        "BooleanExpression" => {
            if structure_owned && composite { names.push("Objects::Object::ownedPerformances"); }
            if behavior_owned && composite { names.push("Performances::Performance::subperformances"); }
            if behavior_owned { names.push("Performances::Performance::enclosedPerformances"); }
        },
        "ConstructorExpression" => {
            if structure_owned && composite { names.push("Objects::Object::ownedPerformances"); }
            if behavior_owned && composite { names.push("Performances::Performance::subperformances"); }
            if behavior_owned { names.push("Performances::Performance::enclosedPerformances"); }
        },
        "Expression" => {
            if structure_owned && composite { names.push("Objects::Object::ownedPerformances"); }
            if behavior_owned && composite { names.push("Performances::Performance::subperformances"); }
            if behavior_owned { names.push("Performances::Performance::enclosedPerformances"); }
        },
        "FeatureReferenceExpression" => {
            if structure_owned && composite { names.push("Objects::Object::ownedPerformances"); }
            if behavior_owned && composite { names.push("Performances::Performance::subperformances"); }
            if behavior_owned { names.push("Performances::Performance::enclosedPerformances"); }
        },
        "Invariant" => {
            if structure_owned && composite { names.push("Objects::Object::ownedPerformances"); }
            if behavior_owned && composite { names.push("Performances::Performance::subperformances"); }
            if behavior_owned { names.push("Performances::Performance::enclosedPerformances"); }
        },
        "LiteralBoolean" => {
            if structure_owned && composite { names.push("Objects::Object::ownedPerformances"); }
            if behavior_owned && composite { names.push("Performances::Performance::subperformances"); }
            if behavior_owned { names.push("Performances::Performance::enclosedPerformances"); }
        },
        "LiteralExpression" => {
            if structure_owned && composite { names.push("Objects::Object::ownedPerformances"); }
            if behavior_owned && composite { names.push("Performances::Performance::subperformances"); }
            if behavior_owned { names.push("Performances::Performance::enclosedPerformances"); }
        },
        "LiteralInfinity" => {
            if structure_owned && composite { names.push("Objects::Object::ownedPerformances"); }
            if behavior_owned && composite { names.push("Performances::Performance::subperformances"); }
            if behavior_owned { names.push("Performances::Performance::enclosedPerformances"); }
        },
        "LiteralInteger" => {
            if structure_owned && composite { names.push("Objects::Object::ownedPerformances"); }
            if behavior_owned && composite { names.push("Performances::Performance::subperformances"); }
            if behavior_owned { names.push("Performances::Performance::enclosedPerformances"); }
        },
        "LiteralRational" => {
            if structure_owned && composite { names.push("Objects::Object::ownedPerformances"); }
            if behavior_owned && composite { names.push("Performances::Performance::subperformances"); }
            if behavior_owned { names.push("Performances::Performance::enclosedPerformances"); }
        },
        "LiteralString" => {
            if structure_owned && composite { names.push("Objects::Object::ownedPerformances"); }
            if behavior_owned && composite { names.push("Performances::Performance::subperformances"); }
            if behavior_owned { names.push("Performances::Performance::enclosedPerformances"); }
        },
        "MetadataAccessExpression" => {
            if structure_owned && composite { names.push("Objects::Object::ownedPerformances"); }
            if behavior_owned && composite { names.push("Performances::Performance::subperformances"); }
            if behavior_owned { names.push("Performances::Performance::enclosedPerformances"); }
        },
        "NullExpression" => {
            if structure_owned && composite { names.push("Objects::Object::ownedPerformances"); }
            if behavior_owned && composite { names.push("Performances::Performance::subperformances"); }
            if behavior_owned { names.push("Performances::Performance::enclosedPerformances"); }
        },
        _ => return None,
    }
    Some(names)
}
