// Generated by tools/generate_expression_redefinitions.py; do not edit.
// Imported transition-guard policy is intentionally not an implemented algorithm.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) enum Relevant { Feature, Empty, TransitionGuard }
pub(super) const EMPTY_OWNER_TYPE: &str = "FeatureValue";
pub(super) const GUARD_MEMBERSHIP: &str = "TransitionFeatureMembership";
pub(super) fn supports(kind: &str) -> bool { matches!(kind, "BooleanExpression" | "CollectExpression" | "ConstructorExpression" | "Expression" | "FeatureChainExpression" | "FeatureReferenceExpression" | "IndexExpression" | "Invariant" | "InvocationExpression" | "LiteralBoolean" | "LiteralExpression" | "LiteralInfinity" | "LiteralInteger" | "LiteralRational" | "LiteralString" | "MetadataAccessExpression" | "NullExpression" | "OperatorExpression" | "SelectExpression" | "TriggerInvocationExpression") }
pub(super) fn is_guard(is_transition_membership: bool, membership_kind: &str) -> bool {
    is_transition_membership && membership_kind == "guard"
}
pub(super) fn relevant(transition_guard: bool, empty_owner_type: bool) -> Relevant {
    if transition_guard { Relevant::TransitionGuard }
    else if empty_owner_type { Relevant::Empty }
    else { Relevant::Feature }
}
