// Generated by tools/generate_feature_chain_members.py; do not edit.
pub(super) const DEFINITION_SHA:&str="7bb309074b92f4d569806a4f0957606d7942c0a60a34db1efcb9b5ec26420e16";
pub(super) const SOURCE_POSITION:usize=0;
pub(super) const SOURCE_NAME:&str="";
pub(super) fn supports(kind:&str)->bool {kind.rsplit("::").next()==Some("FeatureChainExpression")}
