// Generated by tools/export_pilot_feature_defaults.py; do not edit.
// Exact Feature selector; guarded native services provide semantic predicate inputs.
pub(super) fn feature_default_name(structure: bool, class: bool, data: bool, subobject: bool, suboccurrence: bool, portion: bool) -> &'static str {
    if structure { if subobject { "Objects::Object::subobjects" } else { "Objects::objects" } }
    else if class { if suboccurrence { "Occurrences::Occurrence::suboccurrences" } else if portion { "Occurrences::Occurrence::portions" } else { "Occurrences::occurrences" } }
    else if data { "Base::dataValues" } else { "Base::things" }
}
pub(super) fn participant_required(association_end: bool, implicit_redefinition: bool) -> bool {
    association_end && !implicit_redefinition
}
pub(super) fn association_default_name(kind: &str, ends: usize) -> Option<&'static str> {
    match (kind, ends == 2) {
        ("Association", false) => Some("Links::Link"),
        ("Association", true) => Some("Links::BinaryLink"),
        ("AssociationStructure", false) => Some("Objects::LinkObject"),
        ("AssociationStructure", true) => Some("Objects::BinaryLinkObject"),
        _ => None,
    }
}
pub(super) fn ordinary_feature_type_binding(kind: &str) -> bool {
    matches!(kind, "Feature" | "ReferenceUsage" | "Usage")
}
pub(super) fn usage_default_name(kind: &str, structure: bool, class: bool, data: bool) -> Option<&'static str> {
    match kind {
        "BindingConnectorAsUsage" => Some(if structure { "Objects::objects" } else if class { "Occurrences::occurrences" } else if data { "Base::dataValues" } else { "Links::selfLinks" }),
        "ReferenceUsage" => Some(if structure { "Objects::objects" } else if class { "Occurrences::occurrences" } else if data { "Base::dataValues" } else { "Base::things" }),
        "Usage" => Some(if structure { "Objects::objects" } else if class { "Occurrences::occurrences" } else if data { "Base::dataValues" } else { "Base::things" }),
        _ => None,
    }
}
pub(super) fn ordinary_usage_binding(kind: &str) -> bool { usage_default_name(kind, false, false, false).is_some() }
pub(super) fn usage_additional_members_required(is_end: bool) -> bool { is_end }
pub(super) fn reference_redefinition_uses_feature(owner_is_transition: bool, is_transition_link: bool) -> bool { !(owner_is_transition && is_transition_link) }
