// Generated by tools/generate_multiplicity_defaults.py; ownership algorithm remains handwritten.
pub(super) const OWNER_CLASSIFIER: &str = "Classifier";
pub(super) const OWNER_FEATURE: &str = "Feature";
pub(super) fn supports(kind:&str)->bool {matches!(kind,"Multiplicity"|"MultiplicityRange")}
pub(super) fn default_name(kind:&str,classifier:bool,feature:bool)->Option<&'static str> {
    Some(match kind {
        "Multiplicity" => if classifier {"Base::zeroOrOne"} else if feature {"Base::exactlyOne"} else {"Base::naturals"},
        "MultiplicityRange" => if classifier {"Base::naturals"} else if feature {"Base::naturals"} else {"Base::naturals"},
        _ => return None,
    })
}
