// Generated by bounded resolved predicate/effect translation, with imported default maps.
// Canonical inputs and Feature/Usage lifecycle admission are handwritten dependencies.
pub(super) struct Inputs<'a> {pub composite:bool,pub structure:bool,pub data:bool,pub owner_kind:&'a str,pub owner_class:bool,pub owner_structure:bool,pub portion:&'a str}
impl Inputs<'_> {fn owner_is(&self,kind:&str)->bool {super::metaclass_conforms(self.owner_kind,kind)}}
pub(super) fn supports(kind:&str)->bool {matches!(kind,"ItemUsage" | "MetadataUsage" | "OccurrenceUsage" | "ViewUsage")}
pub(super) fn names(kind:&str,c:&Inputs<'_>)->Option<Vec<&'static str>> {
let mut roles=Vec::new();match kind {
"ItemUsage" => {
    roles.push(if c.composite && (c.owner_is("ItemDefinition") || c.owner_is("ItemUsage")) { "subitem" } else { "base" });
    if c.data {
        roles.push("dataValue");
    }
    if c.structure {
        roles.push(if (c.composite && (c.owner_is("Structure") || (c.owner_is("Feature") && c.owner_structure))) && (!(c.composite && (c.owner_is("ItemDefinition") || c.owner_is("ItemUsage")))) { "subobject" } else { "object" });
    } else {
        if ((c.composite && (c.owner_is("Class") || (c.owner_is("Feature") && c.owner_class))) || (c.composite && c.owner_is("OccurrenceUsage"))) && (!(c.composite && (c.owner_is("ItemDefinition") || c.owner_is("ItemUsage")))) {
            roles.push("suboccurrence");
        }
    }
    if c.portion == "snapshot" {
        roles.push("snapshot");
    } else {
        if c.portion == "timeslice" {
            roles.push("timeslice");
        }
    }
},
"MetadataUsage" => {
    roles.push("base");
    if c.data {
        roles.push("dataValue");
    }
    if c.structure {
        roles.push(if (c.composite && (c.owner_is("Structure") || (c.owner_is("Feature") && c.owner_structure))) && (!(c.composite && (c.owner_is("ItemDefinition") || c.owner_is("ItemUsage")))) { "subobject" } else { "object" });
    } else {
        if ((c.composite && (c.owner_is("Class") || (c.owner_is("Feature") && c.owner_class))) || (c.composite && c.owner_is("OccurrenceUsage"))) && (!(c.composite && (c.owner_is("ItemDefinition") || c.owner_is("ItemUsage")))) {
            roles.push("suboccurrence");
        }
    }
    if c.portion == "snapshot" {
        roles.push("snapshot");
    } else {
        if c.portion == "timeslice" {
            roles.push("timeslice");
        }
    }
},
"OccurrenceUsage" => {
    roles.push("base");
    if c.data {
        roles.push("dataValue");
    }
    if c.structure {
        roles.push(if c.composite && (c.owner_is("Structure") || (c.owner_is("Feature") && c.owner_structure)) { "subobject" } else { "object" });
    } else {
        if (c.composite && (c.owner_is("Class") || (c.owner_is("Feature") && c.owner_class))) || (c.composite && c.owner_is("OccurrenceUsage")) {
            roles.push("suboccurrence");
        }
    }
    if c.portion == "snapshot" {
        roles.push("snapshot");
    } else {
        if c.portion == "timeslice" {
            roles.push("timeslice");
        }
    }
},
"ViewUsage" => {
    roles.push(if c.owner_is("ViewDefinition") || c.owner_is("ViewUsage") { "subview" } else { "base" });
    if c.data {
        roles.push("dataValue");
    }
    if c.structure {
        roles.push(if (c.composite && (c.owner_is("Structure") || (c.owner_is("Feature") && c.owner_structure))) && (!(c.composite && (c.owner_is("ItemDefinition") || c.owner_is("ItemUsage")))) { "subobject" } else { "object" });
    } else {
        if ((c.composite && (c.owner_is("Class") || (c.owner_is("Feature") && c.owner_class))) || (c.composite && c.owner_is("OccurrenceUsage"))) && (!(c.composite && (c.owner_is("ItemDefinition") || c.owner_is("ItemUsage")))) {
            roles.push("suboccurrence");
        }
    }
    if c.portion == "snapshot" {
        roles.push("snapshot");
    } else {
        if c.portion == "timeslice" {
            roles.push("timeslice");
        }
    }
    if c.composite && (c.owner_is("ItemDefinition") || c.owner_is("ItemUsage")) {
        roles.push("subpart");
    }
},
_ => return None,
}
let mut names=Vec::new();for role in roles {let name=match (kind,role) {
("ItemUsage","base") => "Items::items",
("ItemUsage","dataValue") => "Base::dataValues",
("ItemUsage","object") => "Objects::objects",
("ItemUsage","snapshot") => "Occurrences::Occurrence::snapshots",
("ItemUsage","subitem") => "Items::Item::subitems",
("ItemUsage","subobject") => "Objects::Object::subobjects",
("ItemUsage","suboccurrence") => "Occurrences::Occurrence::suboccurrences",
("ItemUsage","timeslice") => "Occurrences::Occurrence::timeSlices",
("MetadataUsage","base") => "Metadata::metadataItems",
("MetadataUsage","dataValue") => "Base::dataValues",
("MetadataUsage","object") => "Objects::objects",
("MetadataUsage","snapshot") => "Occurrences::Occurrence::snapshots",
("MetadataUsage","subitem") => "Items::Item::subitems",
("MetadataUsage","subobject") => "Objects::Object::subobjects",
("MetadataUsage","suboccurrence") => "Occurrences::Occurrence::suboccurrences",
("MetadataUsage","timeslice") => "Occurrences::Occurrence::timeSlices",
("OccurrenceUsage","base") => "Occurrences::occurrences",
("OccurrenceUsage","dataValue") => "Base::dataValues",
("OccurrenceUsage","object") => "Objects::objects",
("OccurrenceUsage","snapshot") => "Occurrences::Occurrence::snapshots",
("OccurrenceUsage","subobject") => "Objects::Object::subobjects",
("OccurrenceUsage","suboccurrence") => "Occurrences::Occurrence::suboccurrences",
("OccurrenceUsage","timeslice") => "Occurrences::Occurrence::timeSlices",
("ViewUsage","base") => "Views::views",
("ViewUsage","dataValue") => "Base::dataValues",
("ViewUsage","object") => "Objects::objects",
("ViewUsage","snapshot") => "Occurrences::Occurrence::snapshots",
("ViewUsage","subitem") => "Items::Item::subparts",
("ViewUsage","subobject") => "Objects::Object::subobjects",
("ViewUsage","suboccurrence") => "Occurrences::Occurrence::suboccurrences",
("ViewUsage","subpart") => "Items::Item::subparts",
("ViewUsage","subview") => "Views::View::subviews",
("ViewUsage","timeslice") => "Occurrences::Occurrence::timeSlices",
_ => return None,};if !names.contains(&name) {names.push(name);}}Some(names)
}
