// Generated by tools/generate_parameter_collections.py; do not edit.
pub(super) const OWNER_0: &str = "Behavior";
pub(super) const OWNER_1: &str = "Step";
pub(super) fn is_parameter(owner_0: bool, owner_1: bool, directed: bool) -> bool {
    (owner_0 || owner_1) && directed
}
