// Generated by tools/generate_relative_namespace.py; do not edit.
pub(super) const DEFINITION_SHA: &str = "4455793c396fb7e1fd10e595508b184a271a65801d3582c3de618d8c66f19dcb";
pub(super) fn dispatch(assignment: bool, chain: bool) -> Option<bool> {
    if assignment {Some(true)} else if chain {Some(false)} else {None}
}
pub(super) fn input_direction(direction: Option<&str>) -> bool {
    matches!(direction,Some("in" | "inout"))
}
