// Generated by tools/generate_step_defaults.py; do not edit.
pub(super) const PAYLOAD_TYPE: &str = "PayloadFeature";
pub(super) fn supports(kind: &str) -> bool { kind == "Step" }
pub(super) fn name(composite: bool, structure_owned: bool, behavior_owned: bool, incoming_transfer: bool) -> &'static str {
    if structure_owned && composite { "Objects::Object::ownedPerformances" } else { if behavior_owned && composite { "Performances::Performance::subperformances" } else { if behavior_owned { "Performances::Performance::enclosedPerformances" } else { if incoming_transfer { "Occurrences::Occurrence::incomingTransfers" } else { "Performances::performances" } } } }
}
