// Generated by tools/generate_type_relationship_scope.py; scoping algorithm remains handwritten.
pub const BINDINGS: &[(&str,&str)] = &[
    ("Differencing","differencing_type"),
    ("Disjoining","disjoining_type"),
    ("Disjoining","type_disjoined"),
    ("Intersecting","intersecting_type"),
    ("Unioning","unioning_type"),
];
pub fn permits(kind:&str,field:&str)->bool {let kind=kind.rsplit("::").next().unwrap_or(kind); BINDINGS.iter().any(|(k,f)|*k==kind && *f==field)}
