// Generated by tools/generate_namespace_grammar_contracts.py; do not edit.
// Source: pinned Xtext AST. Procedural semantics remain separate.
pub(crate) const SYSML_ANNOTATING_KINDS: &[&str] = &["SysML::Comment", "SysML::Documentation", "SysML::TextualRepresentation", "SysML::MetadataUsage"];
pub(crate) const SYSML_RELATIONSHIP_BODY_FIELDS: &[&str] = &["ownedRelationship"];
pub(crate) const SYSML_MEMBERSHIPIMPORT: &str = "SysML::MembershipImport";
pub(crate) const SYSML_NAMESPACEIMPORT: &str = "SysML::NamespaceImport";
pub(crate) const SYSML_MEMBERSHIPEXPOSE: &str = "SysML::MembershipExpose";
pub(crate) const SYSML_NAMESPACEEXPOSE: &str = "SysML::NamespaceExpose";
pub(crate) const KERML_ANNOTATING_KINDS: &[&str] = &["SysML::Comment", "SysML::Documentation", "SysML::TextualRepresentation", "SysML::MetadataFeature"];
pub(crate) const KERML_RELATIONSHIP_BODY_FIELDS: &[&str] = &["ownedRelatedElement", "ownedRelationship"];
pub(crate) const KERML_OWNED_ELEMENT_RULES: &[&str] = &["Dependency", "Namespace", "Package", "LibraryPackage", "Multiplicity", "Type", "Classifier", "Class", "Structure", "Metaclass", "DataType", "Association", "AssociationStructure", "Interaction", "Behavior", "Function", "Predicate", "Specialization", "Conjugation", "FeatureTyping", "Subclassification", "Disjoining", "FeatureInverting", "Subsetting", "Redefinition", "TypeFeaturing", "Feature", "Step", "Expression", "BooleanExpression", "Invariant", "Connector", "BindingConnector", "Succession", "Flow", "SuccessionFlow"];
pub(crate) const KERML_MEMBERSHIPIMPORT: &str = "SysML::MembershipImport";
pub(crate) const KERML_NAMESPACEIMPORT: &str = "SysML::NamespaceImport";
pub(crate) const EXPOSE_VISIBILITY: &str = "protected";
