// @generated by tools/generate_validation_rust.py; do not edit.
// Regenerate: python -B tools/generate_validation_rust.py
// Typed IR SHA-256: b70a4972a20174c99fc541c003f04f0ac4abe6acf987318921842baa541bd559
// Generator SHA-256: 16a60e9a691a92cc79efd7aa2ae909c03fc3d6b1546753a9c162b4dfc69c97dd
// Semantic getters and shared value contracts are handwritten Rust.
use super::{SemanticModel, Value, RuleDiagnostic, require_getters, read_getter, identity_equal};
use super::instance_of;

pub(super) fn evaluate(
    name: &str,
    subject: &str,
    model: &impl SemanticModel,
) -> Result<Vec<RuleDiagnostic>, String> {
    match name {
        "org.omg.kerml.xtext.validation.KerMLValidator#checkAnnotation" | "checkAnnotation" => rule_0000(subject, model),
        "org.omg.kerml.xtext.validation.KerMLValidator#checkImport" | "checkImport" => rule_0001(subject, model),
        "org.omg.sysml.xtext.validation.SysMLValidator#checkAnalysisCaseUsage" | "checkAnalysisCaseUsage" => rule_0002(subject, model),
        "org.omg.sysml.xtext.validation.SysMLValidator#checkEnumerationDefinition" | "checkEnumerationDefinition" => rule_0003(subject, model),
        "org.omg.sysml.xtext.validation.SysMLValidator#checkEnumerationUsage" | "checkEnumerationUsage" => rule_0004(subject, model),
        "org.omg.sysml.xtext.validation.SysMLValidator#checkMetadataUsage" | "checkMetadataUsage" => rule_0005(subject, model),
        "org.omg.sysml.xtext.validation.SysMLValidator#checkReferenceUsage" | "checkReferenceUsage" => rule_0006(subject, model),
        "org.omg.sysml.xtext.validation.SysMLValidator#checkRenderingUsage" | "checkRenderingUsage" => rule_0007(subject, model),
        "org.omg.sysml.xtext.validation.SysMLValidator#checkUseCaseUsage" | "checkUseCaseUsage" => rule_0008(subject, model),
        "org.omg.sysml.xtext.validation.SysMLValidator#checkVerificationCaseUsage" | "checkVerificationCaseUsage" => rule_0009(subject, model),
        "org.omg.sysml.xtext.validation.SysMLValidator#checkViewpointUsage" | "checkViewpointUsage" => rule_0010(subject, model),
        _ => Err(format!("unknown generated validation rule {name}")),
    }
}

fn rule_0000(
    subject: &str,
    model: &impl SemanticModel,
) -> Result<Vec<RuleDiagnostic>, String> {
    require_getters("org.omg.kerml.xtext.validation.KerMLValidator#checkAnnotation", &[
        "org.omg.sysml.lang.sysml.Annotation.getOwnedAnnotatingElement()",
        "org.omg.sysml.lang.sysml.Annotation.getOwningAnnotatedElement()",
        "org.omg.sysml.lang.sysml.Annotation.getOwningAnnotatingElement()",
    ], model)?;
    let subject_value = Value::object(subject, "org.omg.sysml.lang.sysml.Annotation");
    let mut diagnostics = Vec::new();
    let local_0 = read_getter(subject_value.clone(), "org.omg.sysml.lang.sysml.Annotation.getOwnedAnnotatingElement()", model)?;
    let local_1 = read_getter(subject_value.clone(), "org.omg.sysml.lang.sysml.Annotation.getOwningAnnotatingElement()", model)?;
    if ((identity_equal(local_0.clone(), Value::Null)?) && (identity_equal(local_1.clone(), Value::Null)?)) || ((!identity_equal(local_0.clone(), Value::Null)?) && (!identity_equal(local_1.clone(), Value::Null)?)) {
        let diagnostic_2_message = (Value::String("Must either own or be owned by its annotating element".into())).string()?;
        let diagnostic_2_subject = (subject_value.clone()).optional_identity()?;
        let diagnostic_2_feature = (Value::Null).optional_identity()?;
        let diagnostic_2_code = (Value::String("validateAnnotationAnnotatingElement".into())).string()?;
        diagnostics.push(RuleDiagnostic {
            severity: "error".into(),
            message: diagnostic_2_message,
            subject: diagnostic_2_subject,
            feature: diagnostic_2_feature,
            code: diagnostic_2_code,
            index: None,
            data: vec![],
        });
    } else {
    }
    let local_3 = read_getter(subject_value.clone(), "org.omg.sysml.lang.sysml.Annotation.getOwningAnnotatedElement()", model)?;
    if (!identity_equal(local_3.clone(), Value::Null)?) && (identity_equal(local_0.clone(), Value::Null)?) {
        let diagnostic_4_message = (Value::String("Must own its annotating element".into())).string()?;
        let diagnostic_4_subject = (subject_value.clone()).optional_identity()?;
        let diagnostic_4_feature = (Value::Null).optional_identity()?;
        let diagnostic_4_code = (Value::String("validateAnnotationAnnotatedElementOwnership".into())).string()?;
        diagnostics.push(RuleDiagnostic {
            severity: "error".into(),
            message: diagnostic_4_message,
            subject: diagnostic_4_subject,
            feature: diagnostic_4_feature,
            code: diagnostic_4_code,
            index: None,
            data: vec![],
        });
    } else {
    }
    if (identity_equal(local_3.clone(), Value::Null)?) && (!identity_equal(local_0.clone(), Value::Null)?) {
        let diagnostic_5_message = (Value::String("Must be owned by its annotated element".into())).string()?;
        let diagnostic_5_subject = (subject_value.clone()).optional_identity()?;
        let diagnostic_5_feature = (Value::Null).optional_identity()?;
        let diagnostic_5_code = (Value::String("validateAnnotationAnnotatedElementOwnership".into())).string()?;
        diagnostics.push(RuleDiagnostic {
            severity: "error".into(),
            message: diagnostic_5_message,
            subject: diagnostic_5_subject,
            feature: diagnostic_5_feature,
            code: diagnostic_5_code,
            index: None,
            data: vec![],
        });
    } else {
    }
    Ok(diagnostics)
}

fn rule_0001(
    subject: &str,
    model: &impl SemanticModel,
) -> Result<Vec<RuleDiagnostic>, String> {
    require_getters("org.omg.kerml.xtext.validation.KerMLValidator#checkImport", &[
        "org.omg.sysml.lang.sysml.Element.getOwner()",
        "org.omg.sysml.lang.sysml.Import.getImportOwningNamespace()",
        "org.omg.sysml.lang.sysml.Import.getVisibility()",
    ], model)?;
    let subject_value = Value::object(subject, "org.omg.sysml.lang.sysml.Import");
    let mut diagnostics = Vec::new();
    if ((!identity_equal(read_getter(subject_value.clone(), "org.omg.sysml.lang.sysml.Import.getImportOwningNamespace()", model)?, Value::Null)?) && (identity_equal(read_getter(read_getter(subject_value.clone(), "org.omg.sysml.lang.sysml.Import.getImportOwningNamespace()", model)?, "org.omg.sysml.lang.sysml.Element.getOwner()", model)?, Value::Null)?)) && (!identity_equal(read_getter(subject_value.clone(), "org.omg.sysml.lang.sysml.Import.getVisibility()", model)?, Value::Enum { type_name: "org.omg.sysml.lang.sysml.VisibilityKind".into(), name: "PRIVATE".into() })?) {
        let diagnostic_0_message = (Value::String("Top level import must be private".into())).string()?;
        let diagnostic_0_subject = (subject_value.clone()).optional_identity()?;
        let diagnostic_0_feature = (Value::Null).optional_identity()?;
        let diagnostic_0_code = (Value::String("validateImportTopLevelVisibility".into())).string()?;
        diagnostics.push(RuleDiagnostic {
            severity: "error".into(),
            message: diagnostic_0_message,
            subject: diagnostic_0_subject,
            feature: diagnostic_0_feature,
            code: diagnostic_0_code,
            index: None,
            data: vec![],
        });
    } else {
    }
    Ok(diagnostics)
}

fn rule_0002(
    subject: &str,
    model: &impl SemanticModel,
) -> Result<Vec<RuleDiagnostic>, String> {
    require_getters("org.omg.sysml.xtext.validation.SysMLValidator#checkAnalysisCaseUsage", &[
        "java.lang.Class.isInstance(java.lang.Object)",
        "org.omg.sysml.util.FeatureUtil.getAllTypesOf(org.omg.sysml.lang.sysml.Feature)",
    ], model)?;
    let subject_value = Value::object(subject, "org.omg.sysml.lang.sysml.AnalysisCaseUsage");
    let mut diagnostics = Vec::new();
    {
        let local_0 = read_getter(subject_value.clone(), "org.omg.sysml.util.FeatureUtil.getAllTypesOf(org.omg.sysml.lang.sysml.Feature)", model)?;
        let local_2 = Value::Bool(((Value::Bool((Value::Int(i32::try_from((local_0.clone()).list()?.len()).map_err(|_| "collection length exceeds Java int")?)).integer()? == (Value::Int(1_i32)).integer()?)).boolean()?) && ((Value::Bool((|| -> Result<bool, String> { for item_1 in (local_0.clone()).list()? { if (Value::Bool(instance_of(item_1.clone(), "org.omg.sysml.lang.sysml.AnalysisCaseDefinition", model)?)).boolean()? { return Ok(true); } } Ok(false) })()?)).boolean()?));
        if !((local_2.clone()).boolean()?) {
            let diagnostic_3_message = (Value::String("An analysis case must be typed by one analysis case definition.".into())).string()?;
            let diagnostic_3_subject = (subject_value.clone()).optional_identity()?;
            let diagnostic_3_feature = (Value::object("AnalysisCaseUsage::analysisCaseDefinition", "org.eclipse.emf.ecore.EReference")).optional_identity()?;
            let diagnostic_3_code = (Value::String("validateAnalysisCaseUsageType_".into())).string()?;
            diagnostics.push(RuleDiagnostic {
                severity: "error".into(),
                message: diagnostic_3_message,
                subject: diagnostic_3_subject,
                feature: diagnostic_3_feature,
                code: diagnostic_3_code,
                index: None,
                data: vec![],
            });
        } else {
        }
        let _ = local_2.clone();
    }
    Ok(diagnostics)
}

fn rule_0003(
    subject: &str,
    model: &impl SemanticModel,
) -> Result<Vec<RuleDiagnostic>, String> {
    require_getters("org.omg.sysml.xtext.validation.SysMLValidator#checkEnumerationDefinition", &[
        "org.omg.sysml.lang.sysml.Definition.isVariation()",
    ], model)?;
    let subject_value = Value::object(subject, "org.omg.sysml.lang.sysml.EnumerationDefinition");
    let mut diagnostics = Vec::new();
    if !((read_getter(subject_value.clone(), "org.omg.sysml.lang.sysml.Definition.isVariation()", model)?).boolean()?) {
        let diagnostic_0_message = (Value::String("An enumeration definition must be a variation.".into())).string()?;
        let diagnostic_0_subject = (subject_value.clone()).optional_identity()?;
        let diagnostic_0_feature = (Value::Null).optional_identity()?;
        let diagnostic_0_code = (Value::String("validateEnumerationDefinitionIsVariation".into())).string()?;
        diagnostics.push(RuleDiagnostic {
            severity: "error".into(),
            message: diagnostic_0_message,
            subject: diagnostic_0_subject,
            feature: diagnostic_0_feature,
            code: diagnostic_0_code,
            index: None,
            data: vec![],
        });
    } else {
    }
    Ok(diagnostics)
}

fn rule_0004(
    subject: &str,
    model: &impl SemanticModel,
) -> Result<Vec<RuleDiagnostic>, String> {
    require_getters("org.omg.sysml.xtext.validation.SysMLValidator#checkEnumerationUsage", &[
        "java.lang.Class.isInstance(java.lang.Object)",
        "org.omg.sysml.util.FeatureUtil.getAllTypesOf(org.omg.sysml.lang.sysml.Feature)",
    ], model)?;
    let subject_value = Value::object(subject, "org.omg.sysml.lang.sysml.EnumerationUsage");
    let mut diagnostics = Vec::new();
    {
        let local_0 = read_getter(subject_value.clone(), "org.omg.sysml.util.FeatureUtil.getAllTypesOf(org.omg.sysml.lang.sysml.Feature)", model)?;
        let local_2 = Value::Bool(((Value::Bool((Value::Int(i32::try_from((local_0.clone()).list()?.len()).map_err(|_| "collection length exceeds Java int")?)).integer()? == (Value::Int(1_i32)).integer()?)).boolean()?) && ((Value::Bool((|| -> Result<bool, String> { for item_1 in (local_0.clone()).list()? { if (Value::Bool(instance_of(item_1.clone(), "org.omg.sysml.lang.sysml.EnumerationDefinition", model)?)).boolean()? { return Ok(true); } } Ok(false) })()?)).boolean()?));
        if !((local_2.clone()).boolean()?) {
            let diagnostic_3_message = (Value::String("An enumeration must be typed by one enumeration definition.".into())).string()?;
            let diagnostic_3_subject = (subject_value.clone()).optional_identity()?;
            let diagnostic_3_feature = (Value::object("EnumerationUsage::enumerationDefinition", "org.eclipse.emf.ecore.EReference")).optional_identity()?;
            let diagnostic_3_code = (Value::String("validateEnumerationUsageType_".into())).string()?;
            diagnostics.push(RuleDiagnostic {
                severity: "error".into(),
                message: diagnostic_3_message,
                subject: diagnostic_3_subject,
                feature: diagnostic_3_feature,
                code: diagnostic_3_code,
                index: None,
                data: vec![],
            });
        } else {
        }
        let _ = local_2.clone();
    }
    Ok(diagnostics)
}

fn rule_0005(
    subject: &str,
    model: &impl SemanticModel,
) -> Result<Vec<RuleDiagnostic>, String> {
    require_getters("org.omg.sysml.xtext.validation.SysMLValidator#checkMetadataUsage", &[
        "java.lang.Class.isInstance(java.lang.Object)",
        "org.omg.sysml.util.FeatureUtil.getAllTypesOf(org.omg.sysml.lang.sysml.Feature)",
    ], model)?;
    let subject_value = Value::object(subject, "org.omg.sysml.lang.sysml.MetadataUsage");
    let mut diagnostics = Vec::new();
    {
        let local_0 = read_getter(subject_value.clone(), "org.omg.sysml.util.FeatureUtil.getAllTypesOf(org.omg.sysml.lang.sysml.Feature)", model)?;
        let local_2 = Value::Bool(((Value::Bool((Value::Int(i32::try_from((local_0.clone()).list()?.len()).map_err(|_| "collection length exceeds Java int")?)).integer()? == (Value::Int(1_i32)).integer()?)).boolean()?) && ((Value::Bool((|| -> Result<bool, String> { for item_1 in (local_0.clone()).list()? { if (Value::Bool(instance_of(item_1.clone(), "org.omg.sysml.lang.sysml.Metaclass", model)?)).boolean()? { return Ok(true); } } Ok(false) })()?)).boolean()?));
        if !((local_2.clone()).boolean()?) {
            let diagnostic_3_message = (Value::String("A metadata usage must be typed by one metadata definition.".into())).string()?;
            let diagnostic_3_subject = (subject_value.clone()).optional_identity()?;
            let diagnostic_3_feature = (Value::object("MetadataUsage::metadataDefinition", "org.eclipse.emf.ecore.EReference")).optional_identity()?;
            let diagnostic_3_code = (Value::String("validateMetadataUsageType_".into())).string()?;
            diagnostics.push(RuleDiagnostic {
                severity: "error".into(),
                message: diagnostic_3_message,
                subject: diagnostic_3_subject,
                feature: diagnostic_3_feature,
                code: diagnostic_3_code,
                index: None,
                data: vec![],
            });
        } else {
        }
        let _ = local_2.clone();
    }
    Ok(diagnostics)
}

fn rule_0006(
    subject: &str,
    model: &impl SemanticModel,
) -> Result<Vec<RuleDiagnostic>, String> {
    require_getters("org.omg.sysml.xtext.validation.SysMLValidator#checkReferenceUsage", &[
        "org.omg.sysml.lang.sysml.Usage.isReference()",
    ], model)?;
    let subject_value = Value::object(subject, "org.omg.sysml.lang.sysml.ReferenceUsage");
    let mut diagnostics = Vec::new();
    if !((read_getter(subject_value.clone(), "org.omg.sysml.lang.sysml.Usage.isReference()", model)?).boolean()?) {
        let diagnostic_0_message = (Value::String("An attribute usage must be referential.".into())).string()?;
        let diagnostic_0_subject = (subject_value.clone()).optional_identity()?;
        let diagnostic_0_feature = (Value::Null).optional_identity()?;
        let diagnostic_0_code = (Value::String("validateAttributeUsageIsReferential".into())).string()?;
        diagnostics.push(RuleDiagnostic {
            severity: "error".into(),
            message: diagnostic_0_message,
            subject: diagnostic_0_subject,
            feature: diagnostic_0_feature,
            code: diagnostic_0_code,
            index: None,
            data: vec![],
        });
    } else {
    }
    Ok(diagnostics)
}

fn rule_0007(
    subject: &str,
    model: &impl SemanticModel,
) -> Result<Vec<RuleDiagnostic>, String> {
    require_getters("org.omg.sysml.xtext.validation.SysMLValidator#checkRenderingUsage", &[
        "java.lang.Class.isInstance(java.lang.Object)",
        "org.omg.sysml.util.FeatureUtil.getAllTypesOf(org.omg.sysml.lang.sysml.Feature)",
    ], model)?;
    let subject_value = Value::object(subject, "org.omg.sysml.lang.sysml.RenderingUsage");
    let mut diagnostics = Vec::new();
    {
        let local_0 = read_getter(subject_value.clone(), "org.omg.sysml.util.FeatureUtil.getAllTypesOf(org.omg.sysml.lang.sysml.Feature)", model)?;
        let local_2 = Value::Bool(((Value::Bool((Value::Int(i32::try_from((local_0.clone()).list()?.len()).map_err(|_| "collection length exceeds Java int")?)).integer()? == (Value::Int(1_i32)).integer()?)).boolean()?) && ((Value::Bool((|| -> Result<bool, String> { for item_1 in (local_0.clone()).list()? { if (Value::Bool(instance_of(item_1.clone(), "org.omg.sysml.lang.sysml.RenderingDefinition", model)?)).boolean()? { return Ok(true); } } Ok(false) })()?)).boolean()?));
        if !((local_2.clone()).boolean()?) {
            let diagnostic_3_message = (Value::String("A rendering must be typed by one rendering definition.".into())).string()?;
            let diagnostic_3_subject = (subject_value.clone()).optional_identity()?;
            let diagnostic_3_feature = (Value::object("RenderingUsage::renderingDefinition", "org.eclipse.emf.ecore.EReference")).optional_identity()?;
            let diagnostic_3_code = (Value::String("validateRenderingUsageType_".into())).string()?;
            diagnostics.push(RuleDiagnostic {
                severity: "error".into(),
                message: diagnostic_3_message,
                subject: diagnostic_3_subject,
                feature: diagnostic_3_feature,
                code: diagnostic_3_code,
                index: None,
                data: vec![],
            });
        } else {
        }
        let _ = local_2.clone();
    }
    Ok(diagnostics)
}

fn rule_0008(
    subject: &str,
    model: &impl SemanticModel,
) -> Result<Vec<RuleDiagnostic>, String> {
    require_getters("org.omg.sysml.xtext.validation.SysMLValidator#checkUseCaseUsage", &[
        "java.lang.Class.isInstance(java.lang.Object)",
        "org.omg.sysml.util.FeatureUtil.getAllTypesOf(org.omg.sysml.lang.sysml.Feature)",
    ], model)?;
    let subject_value = Value::object(subject, "org.omg.sysml.lang.sysml.UseCaseUsage");
    let mut diagnostics = Vec::new();
    {
        let local_0 = read_getter(subject_value.clone(), "org.omg.sysml.util.FeatureUtil.getAllTypesOf(org.omg.sysml.lang.sysml.Feature)", model)?;
        let local_2 = Value::Bool(((Value::Bool((Value::Int(i32::try_from((local_0.clone()).list()?.len()).map_err(|_| "collection length exceeds Java int")?)).integer()? == (Value::Int(1_i32)).integer()?)).boolean()?) && ((Value::Bool((|| -> Result<bool, String> { for item_1 in (local_0.clone()).list()? { if (Value::Bool(instance_of(item_1.clone(), "org.omg.sysml.lang.sysml.UseCaseDefinition", model)?)).boolean()? { return Ok(true); } } Ok(false) })()?)).boolean()?));
        if !((local_2.clone()).boolean()?) {
            let diagnostic_3_message = (Value::String("A use case must be typed by one use case definition.".into())).string()?;
            let diagnostic_3_subject = (subject_value.clone()).optional_identity()?;
            let diagnostic_3_feature = (Value::object("UseCaseUsage::useCaseDefinition", "org.eclipse.emf.ecore.EReference")).optional_identity()?;
            let diagnostic_3_code = (Value::String("validateUseCaseUsageType_".into())).string()?;
            diagnostics.push(RuleDiagnostic {
                severity: "error".into(),
                message: diagnostic_3_message,
                subject: diagnostic_3_subject,
                feature: diagnostic_3_feature,
                code: diagnostic_3_code,
                index: None,
                data: vec![],
            });
        } else {
        }
        let _ = local_2.clone();
    }
    Ok(diagnostics)
}

fn rule_0009(
    subject: &str,
    model: &impl SemanticModel,
) -> Result<Vec<RuleDiagnostic>, String> {
    require_getters("org.omg.sysml.xtext.validation.SysMLValidator#checkVerificationCaseUsage", &[
        "java.lang.Class.isInstance(java.lang.Object)",
        "org.omg.sysml.util.FeatureUtil.getAllTypesOf(org.omg.sysml.lang.sysml.Feature)",
    ], model)?;
    let subject_value = Value::object(subject, "org.omg.sysml.lang.sysml.VerificationCaseUsage");
    let mut diagnostics = Vec::new();
    {
        let local_0 = read_getter(subject_value.clone(), "org.omg.sysml.util.FeatureUtil.getAllTypesOf(org.omg.sysml.lang.sysml.Feature)", model)?;
        let local_2 = Value::Bool(((Value::Bool((Value::Int(i32::try_from((local_0.clone()).list()?.len()).map_err(|_| "collection length exceeds Java int")?)).integer()? == (Value::Int(1_i32)).integer()?)).boolean()?) && ((Value::Bool((|| -> Result<bool, String> { for item_1 in (local_0.clone()).list()? { if (Value::Bool(instance_of(item_1.clone(), "org.omg.sysml.lang.sysml.VerificationCaseDefinition", model)?)).boolean()? { return Ok(true); } } Ok(false) })()?)).boolean()?));
        if !((local_2.clone()).boolean()?) {
            let diagnostic_3_message = (Value::String("A verification case must be typed by one verification case definition.".into())).string()?;
            let diagnostic_3_subject = (subject_value.clone()).optional_identity()?;
            let diagnostic_3_feature = (Value::object("VerificationCaseUsage::verificationCaseDefinition", "org.eclipse.emf.ecore.EReference")).optional_identity()?;
            let diagnostic_3_code = (Value::String("validateVerificationCaseUsageType_".into())).string()?;
            diagnostics.push(RuleDiagnostic {
                severity: "error".into(),
                message: diagnostic_3_message,
                subject: diagnostic_3_subject,
                feature: diagnostic_3_feature,
                code: diagnostic_3_code,
                index: None,
                data: vec![],
            });
        } else {
        }
        let _ = local_2.clone();
    }
    Ok(diagnostics)
}

fn rule_0010(
    subject: &str,
    model: &impl SemanticModel,
) -> Result<Vec<RuleDiagnostic>, String> {
    require_getters("org.omg.sysml.xtext.validation.SysMLValidator#checkViewpointUsage", &[
        "java.lang.Class.isInstance(java.lang.Object)",
        "org.omg.sysml.util.FeatureUtil.getAllTypesOf(org.omg.sysml.lang.sysml.Feature)",
    ], model)?;
    let subject_value = Value::object(subject, "org.omg.sysml.lang.sysml.ViewpointUsage");
    let mut diagnostics = Vec::new();
    {
        let local_0 = read_getter(subject_value.clone(), "org.omg.sysml.util.FeatureUtil.getAllTypesOf(org.omg.sysml.lang.sysml.Feature)", model)?;
        let local_2 = Value::Bool(((Value::Bool((Value::Int(i32::try_from((local_0.clone()).list()?.len()).map_err(|_| "collection length exceeds Java int")?)).integer()? == (Value::Int(1_i32)).integer()?)).boolean()?) && ((Value::Bool((|| -> Result<bool, String> { for item_1 in (local_0.clone()).list()? { if (Value::Bool(instance_of(item_1.clone(), "org.omg.sysml.lang.sysml.ViewpointDefinition", model)?)).boolean()? { return Ok(true); } } Ok(false) })()?)).boolean()?));
        if !((local_2.clone()).boolean()?) {
            let diagnostic_3_message = (Value::String("A viewpoint must be typed by one viewpoint definition.".into())).string()?;
            let diagnostic_3_subject = (subject_value.clone()).optional_identity()?;
            let diagnostic_3_feature = (Value::object("ViewpointUsage::viewpointDefinition", "org.eclipse.emf.ecore.EReference")).optional_identity()?;
            let diagnostic_3_code = (Value::String("validateViewpointUsageType_".into())).string()?;
            diagnostics.push(RuleDiagnostic {
                severity: "error".into(),
                message: diagnostic_3_message,
                subject: diagnostic_3_subject,
                feature: diagnostic_3_feature,
                code: diagnostic_3_code,
                index: None,
                data: vec![],
            });
        } else {
        }
        let _ = local_2.clone();
    }
    Ok(diagnostics)
}

pub(super) fn type_family_rules() -> &'static [(&'static str, &'static str)] { &[
    ("org.omg.sysml.lang.sysml.AnalysisCaseUsage", "checkAnalysisCaseUsage"),
    ("org.omg.sysml.lang.sysml.EnumerationUsage", "checkEnumerationUsage"),
    ("org.omg.sysml.lang.sysml.MetadataUsage", "checkMetadataUsage"),
    ("org.omg.sysml.lang.sysml.RenderingUsage", "checkRenderingUsage"),
    ("org.omg.sysml.lang.sysml.UseCaseUsage", "checkUseCaseUsage"),
    ("org.omg.sysml.lang.sysml.VerificationCaseUsage", "checkVerificationCaseUsage"),
    ("org.omg.sysml.lang.sysml.ViewpointUsage", "checkViewpointUsage"),
] }
