[package]
name = "mercurio-sysml"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
keywords = ["modeling", "sysml", "kerml", "simulation"]
categories = ["parser-implementations", "development-tools"]

[features]
default = ["embed-stdlib"]
embed-stdlib = []

[dependencies]
mercurio-foundation = { path = "../../../mercurio-foundation/crates/mercurio-foundation", version = "0.86.0" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[build-dependencies]
mercurio-foundation = { path = "../../../mercurio-foundation/crates/mercurio-foundation", version = "0.86.0" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
