// Input SHA256: 5fdaa59f5f5aa44b604394c6193d94e9fc5f34ad349df17d8f08d718cabe18b7
// Generated by tools/generate_constructor_constants.py; do not edit.
// javac resolves the constant assignment; superclass/delegate semantics are separate.
pub(super) const VALUES: &[(&str, &str, &str)] = &[
    ("CollectExpression", "operator", "collect"),
    ("FeatureChainExpression", "operator", "."),
    ("IndexExpression", "operator", "#"),
    ("SelectExpression", "operator", "select"),
];
