// Input SHA256: a2ad1ef12f1c1f8199b321668e3479baa807e12d844291db7001e672d9077d68
// Generated by tools/generate_required_feature_dependencies.py; do not edit.
// Observed constructor dependencies, not implemented default algorithms.
pub(super) const CONSTRUCTOR_DEPENDENCIES: &[(&str, &str)] = &[
    ("CollectExpression", "operator"),
    ("FeatureChainExpression", "operator"),
    ("IndexExpression", "operator"),
    ("SelectExpression", "operator"),
];
