"""Bind resolved upstream converters to explicit bounded native algorithms."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROFILE = ROOT / "crates/mercurio-sysml/resources/metamodels/sysml-2.0-pilot-2026-08"
SOURCE = PROFILE / "value-converter-dispatch.extract.json"
OUTPUT = ROOT / "crates/mercurio-sysml/src/xtext_value_dispatch_generated.rs"
ECORE = "http://www.eclipse.org/emf/2002/Ecore#//"
SERVICE = "org.omg.kerml.xtext.conversion.KerMLValueConverterService"
PREFIX = "org.eclipse.xtext.conversion.impl."
CONTEXTS = {"org.omg.kerml.xtext.KerML": "true", "org.omg.sysml.xtext.SysML": "false"}


def render(doc, grammar, ecore):
    if doc["schema_version"] != 1 or doc["provenance"]["pilot_revision"] != "692170b71867353b8f90341e61556f49a5beb0e5":
        raise ValueError("Changed converter schema or pin")
    classes = {row["id"] for row in ecore["classes"]}
    grammars = {row["id"]: row for row in grammar["grammars"]}
    expected = {}
    for context in CONTEXTS:
        visited = set()
        def collect(identity):
            if identity in visited: return
            visited.add(identity)
            item = grammars[identity]
            for rule in item["rules"]:
                datatype = rule["fields"]["type"]["fields"]["classifier"]["$ref"]
                if datatype not in classes:
                    expected[context, rule["id"]] = datatype
            for parent in item["fields"]["usedGrammars"]: collect(parent["$ref"])
        collect(context)
    bindings = {}
    for row in doc["bindings"]:
        key = row["context"], row["rule"]
        if key in bindings: raise ValueError("Duplicate converter binding")
        if expected.get(key) != row["datatype"]: raise ValueError("Changed resolved converter type")
        if row["service"] != SERVICE: raise ValueError("Unassessed converter service")
        converter, datatype = row["converter"], row["datatype"]
        if converter == "org.omg.kerml.xtext.conversion.NonuniqueValueConverter" and datatype == ECORE+"EBoolean":
            algorithm = "Nonunique"
        elif converter in (PREFIX+"EFactoryValueConverter", PREFIX+"DefaultTerminalConverter"):
            algorithm = {ECORE+"EString":"Identity", ECORE+"EInt":"Integer", ECORE+"EDouble":"FiniteDouble", ECORE+"EBoolean":"Boolean"}.get(datatype)
            if algorithm is None and datatype.startswith("https://www.omg.org/spec/SysML/20250201#//"):
                algorithm = "Identity"
        elif converter == "org.eclipse.xtext.conversion.IValueConverter$1" and datatype.startswith("https://www.omg.org/spec/SysML/20250201#//"):
            algorithm = "Identity"
        else: algorithm = None
        if algorithm is None: raise ValueError("Unassessed converter algorithm")
        bindings[key] = (datatype, algorithm)
    if set(bindings) != set(expected): raise ValueError("Incomplete converter inventory")
    lines = ["// Generated by tools/generate_value_converter_dispatch.py; do not edit.",
             "// Selection is upstream-resolved. Algorithms and domain limits are handwritten.",
             "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
             "pub(super) enum Algorithm { Identity, Integer, FiniteDouble, Boolean, Nonunique }",
             "pub(super) fn algorithm(kerml: bool, rule: &str, datatype: &str) -> Option<Algorithm> {",
             "    use Algorithm::*;", "    Some(match (kerml, rule, datatype) {"]
    for (context, rule), (datatype, algorithm) in sorted(bindings.items()):
        lines.append(f'        ({CONTEXTS[context]}, "{rule}", "{datatype}") => {algorithm},')
    lines.extend(["        _ => return None,", "    })", "}", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    raw = SOURCE.read_bytes()
    doc = json.loads(raw)
    for field, name in (("grammar_sha256", "grammar.structure.extract.json"), ("ecore_sha256", "ecore-effective.extract.json")):
        if doc["provenance"][field] != hashlib.sha256((PROFILE/name).read_bytes()).hexdigest():
            raise ValueError("Stale resolved converter provenance: "+field)
    output = "// Input SHA256: "+hashlib.sha256(raw).hexdigest()+"\n"+render(json.loads(raw),
        json.loads((PROFILE/"grammar.structure.extract.json").read_bytes()),
        json.loads((PROFILE/"ecore-effective.extract.json").read_bytes()))
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != output: raise ValueError("Stale native converter dispatch")
    else: OUTPUT.write_text(output, encoding="utf-8", newline="\n")
    print("Native converter dispatch current; finite-double and grammar admission limits remain explicit")

if __name__ == "__main__": main()
