"""Generate all pinned Xtext enum keyword mappings resolved to Ecore literals."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROFILE = ROOT / 'crates/mercurio-sysml/resources/metamodels/sysml-2.0-pilot-2026-08'
GRAMMAR = PROFILE / 'grammar.structure.extract.json'
ECORE = PROFILE / 'ecore-semantics.extract.json'
OUTPUT = PROFILE / 'enum-rules.extract.json'
RUST = ROOT / 'crates/mercurio-sysml/src/enum_grammar_generated.rs'
URI = 'https://www.omg.org/spec/SysML/20250201#//'


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def extract(grammar, ecore):
    enums = {row['id']: row for row in ecore['elements'] if row['kind'] == 'EEnum'}
    literals = {(row['owner'], row['name']): row for row in ecore['elements']
                if row['kind'] == 'EEnumLiteral'}
    if len(enums) != 7 or len(literals) != 19:
        raise ValueError('Pinned Ecore enum inventory changed')
    rules = []
    for language in grammar['grammars']:
        for rule in language['rules']:
            if rule['kind'] != 'EnumRule':
                continue
            enum_type = rule['fields']['type']['fields']['classifier']['$ref']
            if enum_type not in enums or not enum_type.startswith(URI):
                raise ValueError('Unresolved enum type: ' + rule['id'])
            alternatives = rule['fields']['alternatives']
            branches = alternatives['fields']['elements'] if alternatives['kind'] == 'Alternatives' else [alternatives]
            mapping = []
            for branch in branches:
                if branch['kind'] != 'EnumLiteralDeclaration':
                    raise ValueError('Unsupported enum rule branch: ' + branch['id'])
                fields = branch['fields']
                if fields['literal']['kind'] != 'Keyword':
                    raise ValueError('Non-keyword enum literal: ' + branch['id'])
                token = fields['literal']['fields']['value']
                reference = fields['enumLiteral']['$ref']
                owner, literal_name = reference.rsplit('/', 1)
                if owner != enum_type or (owner, literal_name) not in literals:
                    raise ValueError('Xtext/Ecore enum identity mismatch: ' + branch['id'])
                literal = literals[(owner, literal_name)]
                mapping.append({'token': token, 'literal': literal_name,
                                'value': int(literal['attributes'].get('value', '0')),
                                'ecore_literal': literal['id']})
            if len({row['token'] for row in mapping}) != len(mapping):
                raise ValueError('Ambiguous enum keyword: ' + rule['id'])
            rules.append({'id': rule['id'], 'language': language['name'], 'name': rule['fields']['name'],
                          'ecore_enum': enum_type, 'literals': mapping})
    if len(rules) != 14 or sum(len(rule['literals']) for rule in rules) != 24:
        raise ValueError('Pinned Xtext enum inventory changed')
    for name in ('VisibilityIndicator', 'FeatureDirection'):
        pair = [rule for rule in rules if rule['name'] == name]
        if len(pair) != 2 or pair[0]['literals'] != pair[1]['literals']:
            raise ValueError('Shared KerML/SysML enum rule drift: ' + name)
    return {'schema': 'dev.mercurio.pinned-enum-rules.v1', 'rules': rules,
            'grammar_sha256': digest(GRAMMAR), 'ecore_sha256': digest(ECORE)}


def rust_source(document):
    lines = ['// Generated by tools/generate_release_enum_rules.py; do not edit.',
             '#[derive(Debug, Clone, Copy, PartialEq, Eq)]',
             'pub(crate) struct EnumKeyword {',
             "    pub language: &'static str,",
             "    pub rule: &'static str,",
             "    pub token: &'static str,",
             "    pub ecore_enum: &'static str,",
             "    pub literal: &'static str,",
             '    pub value: i32,',
             '}',
             'pub(crate) const ENUM_KEYWORDS: &[EnumKeyword] = &[']
    for rule in document['rules']:
        for literal in rule['literals']:
            fields = [rule['language'], rule['name'], literal['token'], rule['ecore_enum'], literal['literal']]
            lines.append('    EnumKeyword { language: ' + json.dumps(fields[0]) + ', rule: ' + json.dumps(fields[1])
                         + ', token: ' + json.dumps(fields[2]) + ', ecore_enum: ' + json.dumps(fields[3])
                         + ', literal: ' + json.dumps(fields[4]) + f", value: {literal['value']} }},")
    lines.extend(['];', ''])
    return '\n'.join(lines).encode()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    document = extract(json.loads(GRAMMAR.read_text(encoding='utf-8')),
                       json.loads(ECORE.read_text(encoding='utf-8')))
    outputs = [(OUTPUT, (json.dumps(document, indent=2) + '\n').encode()), (RUST, rust_source(document))]
    for path, content in outputs:
        if args.check:
            if path.read_bytes() != content:
                raise ValueError('Stale generated enum rules: ' + str(path))
        else:
            path.write_bytes(content)
    print(f"Pinned enum rules current: {len(document['rules'])} rules, "
          f"{sum(len(row['literals']) for row in document['rules'])} literals")


if __name__ == '__main__':
    main()
