"""Generate bounded selectors from resolved pinned Java semantic programs.
Graph navigation, delegates and lifecycle execution are explicitly handwritten.
"""
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
INPUT=ROOT/'docs/conformance/2026-08-support/relative-namespace-pilot-controls.json'
OUTPUT=ROOT/'crates/mercurio-sysml/src/language_frontend/lowering/emit/relative_namespace_generated.rs'
EXPECTED={'org.omg.sysml.delegate.setting.AssignmentActionUsage_targetArgument_SettingDelegate#basicGet': 'd1ed65b490d934e54ccf8350a40411c946776f9cb518a7a3000a27ae14277772', 'org.omg.sysml.util.ExpressionUtil#addArguments': 'e6cce0de38dcc370425ee63c879c6d9ba498c369121229edd8679d32b1492556', 'org.omg.sysml.util.ExpressionUtil#getArgumentOf': '6e5946149dc0ba4f88ffa55d09e0e70fb4ea7bdbaed35057c13415e577f9a4cd', 'org.omg.sysml.util.FeatureUtil#getValuationFor': '02fead2a38999dd9485274bf549cefffd33743d660e227307432b4272e474988', 'org.omg.sysml.util.FeatureUtil#getValueExpressionFor': '7c1de58ba4b402b836b8209348792586b8e2d3b050475c7b812e8b68f29db640', 'org.omg.sysml.util.FeatureUtil#isInputParameter': 'df8d5daaca28d4b25f61a94dcbc1997c2267ad83c64d2315d3390c207f9521ef', 'org.omg.sysml.util.NamespaceUtil#getRelativeNamespaceFor': '005129b2c0bc9552ecd666980f68ac8bc9e96a9ff5f1543e5047a594b6a9d27d', 'org.omg.sysml.util.NamespaceUtil#getResultNamespaceFor': '78469815e929cbbbddda5b54a70026c545003d2f20a4bb9b02b5e07674f7d8bb', 'org.omg.sysml.util.TypeUtil#getInputOf': 'd078d3f76f5c2c300c446c3ebb39d25174e6cffa9f64d946618bb31be2a79449'}
def generate(data):
    if data.get('schema')!='dev.mercurio.relative-namespace-controls.v1':raise ValueError('Wrong resolved program schema')
    actual={k:hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':')).encode()).hexdigest() for k,v in data['methods'].items()}
    if actual!=EXPECTED:raise ValueError('Unassessed relative namespace semantic program')
    tree=data['methods']['org.omg.sysml.util.NamespaceUtil#getRelativeNamespaceFor']
    def walk(node):
        yield node
        for child in node.get('children',[]):yield from walk(child)
    nodes=list(walk(tree))
    kinds=[n['type'] for n in nodes if n['kind']=='IDENTIFIER' and n.get('type') in ['org.omg.sysml.lang.sysml.AssignmentActionUsage','org.omg.sysml.lang.sysml.FeatureChainExpression']]
    if not set(kinds)=={'org.omg.sysml.lang.sysml.AssignmentActionUsage','org.omg.sysml.lang.sysml.FeatureChainExpression'}:raise ValueError('Unresolved relative namespace dispatch')
    sha=hashlib.sha256(json.dumps(data['methods'],sort_keys=True,separators=(',',':')).encode()).hexdigest()
    return '// Generated by tools/generate_relative_namespace.py; do not edit.\n'+f'pub(super) const DEFINITION_SHA: &str = "{sha}";\n'+'pub(super) fn dispatch(assignment: bool, chain: bool) -> Option<bool> {\n    if assignment {Some(true)} else if chain {Some(false)} else {None}\n}\npub(super) fn input_direction(direction: Option<&str>) -> bool {\n    matches!(direction,Some("in" | "inout"))\n}\n'
def main():
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args()
    text=generate(json.loads(INPUT.read_text(encoding='utf-8')))
    if args.check:
        if OUTPUT.read_text(encoding='utf-8')!=text:raise ValueError('Stale generated relative namespace selectors')
    else:OUTPUT.write_text(text,encoding='utf-8',newline='\n')
if __name__=='__main__':main()
