"""Generate native class conformance from the resolved pinned EMF hierarchy."""
import argparse
import json
import hashlib
from export_pilot_ecore_effective import PROFILE, ROOT, cross_check

INPUT=PROFILE/'ecore-effective.extract.json'
OUTPUT=ROOT/'crates/mercurio-sysml/src/language_frontend/lowering/ecore_hierarchy_generated.rs'
URI='https://www.omg.org/spec/SysML/20250201#//'


def hierarchy(doc):
    rows={r['id']:r for r in doc['classes']}
    if len(rows)!=len(doc['classes']):raise ValueError('Duplicate class identity')
    result={}
    active=set()
    def ancestors(key):
        if key in result:return result[key]
        if key in active:raise ValueError('Cyclic Ecore inheritance: '+key)
        if key not in rows:raise ValueError('Unresolved superclass: '+key)
        if not key.startswith(URI):raise ValueError('Unsupported class namespace: '+key)
        active.add(key)
        values={key}
        for parent in rows[key]['super_types']:values.update(ancestors(parent))
        active.remove(key)
        result[key]=values
        return values
    for key in rows:ancestors(key)
    return {key.removeprefix(URI):sorted(v.removeprefix(URI) for v in values) for key,values in sorted(result.items())}


def generate(doc):
    mapping=hierarchy(doc)
    lines=['// Generated by tools/generate_ecore_hierarchy.py; do not edit.',
           '// Resolved EMF input SHA256: '+hashlib.sha256(json.dumps(doc,sort_keys=True).encode()).hexdigest(),
           '// Class conformance only; construction flags and derived algorithms remain separate.',
           'pub(super) const CLASSES: &[&str] = &[']
    for kind in mapping:
        lines.append('    '+json.dumps(kind)+',')
    lines += ['];',
           'pub(super) fn conforms(kind: &str, base: &str) -> bool {',
           '    match kind {']
    for kind,parents in mapping.items():
        lines.append('        '+json.dumps(kind)+' => matches!(base, '+' | '.join(json.dumps(p) for p in parents)+'),')
    lines += ['        _ => false,','    }','}','']
    return '\n'.join(lines).encode()


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');args=p.parse_args()
    doc=json.loads(INPUT.read_text(encoding='utf-8'))
    cross_check(doc,json.loads((PROFILE/'metamodel.extract.json').read_text(encoding='utf-8')))
    data=generate(doc)
    if args.check:
        if OUTPUT.read_bytes()!=data:raise ValueError('Stale native Ecore hierarchy')
    else:OUTPUT.write_bytes(data)
    print('Native hierarchy current:',len(doc['classes']),'resolved classes')


if __name__=='__main__':main()
