"""Bounded generation from resolved Pilot expression selector trees.

The guard branch is imported but deliberately returned as an unsupported policy;
this module does not implement its library/general-type algorithm.
"""
import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / 'docs/conformance/2026-08-support/expression-redefinition-pilot-controls.json'
BINDINGS = ROOT / 'crates/mercurio-sysml/resources/metamodels/sysml-2.0-pilot-2026-08/feature-redefinitions.extract.json'
OUTPUT = ROOT / 'crates/mercurio-sysml/src/language_frontend/lowering/emit/expression_redefinitions_generated.rs'
PREFIX = 'org.omg.sysml.'


def require(condition, message):
    if not condition:
        raise ValueError(message)


def canonical(node):
    """Remove only javac's unstable capture numbering, preserving resolved types."""
    if isinstance(node, dict):
        return {k: canonical(v) for k, v in node.items()}
    if isinstance(node, list):
        return [canonical(v) for v in node]
    if isinstance(node, str):
        return re.sub(r'capture#\d+', 'capture#N', node)
    return node


def generate(data, bindings):
    methods = data['methods']
    selector = methods[PREFIX + 'adapter.ExpressionAdapter#getRelevantFeatures']
    guard = methods[PREFIX + 'util.ExpressionUtil#isTransitionGuard']
    # A bounded, reviewed tree contract covers every branch, receiver, argument,
    # local and resolved type. Changed upstream algorithms require a new review,
    # not a permissive text recognizer. Capture IDs are the sole normalization.
    shape = json.dumps(canonical(methods), sort_keys=True, separators=(',', ':')).encode()
    require(hashlib.sha256(shape).hexdigest() == TREE_CONTRACT, 'Resolved selector tree changed; review required')
    rows = [r for r in bindings['bindings'] if r['methods']['getRelevantFeatures'] == PREFIX + 'adapter.ExpressionAdapter#getRelevantFeatures']
    kinds = sorted(r['kind'] for r in rows)
    require(len(kinds) == 20 and len(set(kinds)) == 20, 'Expression binding inventory changed')
    require(sorted(data['bindings']) == kinds, 'Probe and adapter binding inventories disagree')
    for row in rows:
        for method in ('addRedefinitions', 'addFeatureWriteTypes', 'addComputedRedefinitions', 'isComputeRedefinitions', 'getRedefinedFeaturesWithComputed'):
            require(row['methods'][method] == PREFIX + 'adapter.FeatureAdapter#' + method, 'Nonordinary inherited algorithm: ' + row['kind'])
        require(row['methods']['getGeneralTypes'] == PREFIX + 'adapter.ExpressionAdapter#getGeneralTypes', 'General-type dispatch changed')
    expected = {(k, o, n) for k in kinds for o in ('detached', 'Package', 'Class') for n in (0, 2)}
    observed = [(c['kind'], c['owner_kind'], c['explicit']) for c in data['controls']]
    require(len(observed) == 120 and set(observed) == expected, 'Incomplete or duplicate ordinary controls')
    expected_guard = {(k, v) for k in kinds for v in ('guard', 'trigger', 'effect')}
    observed_guard = [(c['kind'], c['membership_kind']) for c in data['guard_controls']]
    require(len(observed_guard) == 60 and set(observed_guard) == expected_guard, 'Incomplete or duplicate guard controls')
    branch = selector['statements'][2]['expression']
    dependency = branch['false']['condition']['test_type'].split('.')[-1]
    guard_expr = guard['statements'][1]['expression']
    membership = guard_expr['left']['expression']['test_type'].split('.')[-1]
    literal = guard_expr['right']['right']['name'].lower()
    # These names are resolved upstream metaclasses/enum literals; native code
    # supplies canonical ownership and validates values using the Ecore contract.
    alternatives = ' | '.join(json.dumps(k) for k in kinds)
    return f'''// Generated by tools/generate_expression_redefinitions.py; do not edit.
// Imported transition-guard policy is intentionally not an implemented algorithm.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) enum Relevant {{ Feature, Empty, TransitionGuard }}
pub(super) const EMPTY_OWNER_TYPE: &str = "{dependency}";
pub(super) const GUARD_MEMBERSHIP: &str = "{membership}";
pub(super) fn supports(kind: &str) -> bool {{ matches!(kind, {alternatives}) }}
pub(super) fn is_guard(is_transition_membership: bool, membership_kind: &str) -> bool {{
    is_transition_membership && membership_kind == "{literal}"
}}
pub(super) fn relevant(transition_guard: bool, empty_owner_type: bool) -> Relevant {{
    if transition_guard {{ Relevant::TransitionGuard }}
    else if empty_owner_type {{ Relevant::Empty }}
    else {{ Relevant::Feature }}
}}
'''


TREE_CONTRACT = '94f0753a77868fd8bf2c5333bf8dfa505e19d9668cd7b38a3add8f547d8e7d77'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = generate(json.loads(INPUT.read_text(encoding='utf-8')), json.loads(BINDINGS.read_text(encoding='utf-8')))
    if args.check:
        require(OUTPUT.read_text(encoding='utf-8') == result, 'Generated expression policy is stale')
    else:
        OUTPUT.write_text(result, encoding='utf-8', newline='\n')
    print('20 expression bindings; 120 ordinary and 60 guard controls; generated policy checked' if args.check else 'Generated bounded expression selector policy')


if __name__ == '__main__':
    main()
