"""Generate a bounded reference-origin selector from resolved grammar/Ecore; origin algorithm is reviewed handwritten policy."""
import argparse,hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
PROFILE=ROOT/'crates/mercurio-sysml/resources/metamodels/sysml-2.0-pilot-2026-08'
CLASSES={'Disjoining','Unioning','Intersecting','Differencing'}
def walk(x):
 if isinstance(x,dict):
  yield x
  for v in x.values():yield from walk(v)
 elif isinstance(x,list):
  for v in x:yield from walk(v)
def derive(grammar,ecore):
 features={(f['owner'].split('#//')[-1],f['name']):f for f in ecore['features']};rows=[]
 for rule in walk(grammar):
  if rule.get('kind')!='ParserRule':continue
  fields=rule['fields'];kind=fields['type']['fields']['classifier']['$ref'].split('#//')[-1]
  if kind not in CLASSES:continue
  for a in walk(fields['alternatives']):
   if a.get('kind')!='Assignment' or a['fields']['terminal'].get('kind')!='CrossReference':continue
   camel=a['fields']['feature'];terminal=a['fields']['terminal'];target=terminal['fields']['type']['fields']['classifier']['$ref'];f=features[(kind,camel)]
   if f['type']!=target or not target.endswith('#//Type') or f['derived'] or f['upper_bound']!=1 or f['kind']!='reference':raise ValueError('Unreviewed Type relationship endpoint contract')
   rows.append({'kind':kind,'field':re.sub(r'(?<!^)(?=[A-Z])','_',camel).lower(),'ecore_feature':f['id'],'target_type':target,'rule':rule['id'],'cross_reference':terminal['id'],'origin':'nearest_containing_namespace','algorithm':'explicit handwritten KerML Element scoping fallback'})
 if len(rows)!=6 or {(r['kind'],r['field']) for r in rows}!={('Disjoining','type_disjoined'),('Disjoining','disjoining_type'),('Unioning','unioning_type'),('Intersecting','intersecting_type'),('Differencing','differencing_type')}:raise ValueError('Changed reviewed grammar binding inventory')
 return sorted(rows,key=lambda r:(r['kind'],r['field'],r['rule']))
def main():
 parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
 paths=[PROFILE/'grammar.structure.extract.json',PROFILE/'ecore-effective.extract.json'];rows=derive(*(json.loads(p.read_text(encoding='utf-8')) for p in paths))
 artifact={'schema':'dev.mercurio.type-relationship-scope.v1','scope':'Five stored reference fields / six grammar occurrences; excludes owned feature-chain transformation and full Type set semantics.','inputs':{p.relative_to(ROOT).as_posix():hashlib.sha256(p.read_bytes()).hexdigest() for p in paths},'bindings':rows}
 fields=sorted({(r['kind'],r['field']) for r in rows})
 rust='// Generated by tools/generate_type_relationship_scope.py; scoping algorithm remains handwritten.\n'
 rust+='pub const BINDINGS: &[(&str,&str)] = &[\n'+''.join(f'    ("{k}","{f}"),\n' for k,f in fields)+'];\n'
 rust+='pub fn permits(kind:&str,field:&str)->bool {let kind=kind.rsplit("::").next().unwrap_or(kind); BINDINGS.iter().any(|(k,f)|*k==kind && *f==field)}\n'
 for path,text in [(PROFILE/'type-relationship-scope.extract.json',json.dumps(artifact,indent=2,ensure_ascii=False)+'\n'),(ROOT/'crates/mercurio-sysml/src/language_frontend/lowering/emit/type_relationship_scope_generated.rs',rust)]:
  if args.check:
   if path.read_text(encoding='utf-8')!=text:raise ValueError('Stale generated selector: '+str(path))
  else:path.write_text(text,encoding='utf-8')
 print('Type relationship scope selector: five fields, six resolved grammar occurrences; algorithm handwritten')
if __name__=='__main__':main()
