"""Admit the resolved non-guard expression positional strategy; traversal stays Rust."""
import argparse,hashlib,json
from pathlib import Path
from generate_expression_redefinitions import canonical,require
ROOT=Path(__file__).resolve().parents[1]
INPUT=ROOT/'docs/conformance/2026-08-support/expression-parameter-pilot-controls.json'
OUTPUT=ROOT/'crates/mercurio-sysml/src/language_frontend/lowering/emit/expression_parameters_generated.rs'
TREE='149d2c74b93491f570e77f7604dbf18c0c516f97e37e6e6502050a1e2daeb49a'
SHAPES=['direct','short','inherited','diamond','private','protected','multiple','chain_equal','chain_distinct','explicit','no_result','result_first']
def generate(d):
 require(d['provenance']['pilot_commit']=='692170b71867353b8f90341e61556f49a5beb0e5','Wrong pin')
 require(d['provenance']['jar_sha256']=='4512852638fc799505fe676955e8c78fedef1f3ce44ec90b57b34c05c31e6945','Wrong jar')
 require(hashlib.sha256(json.dumps(canonical(d['methods']),sort_keys=True,separators=(',',':')).encode()).hexdigest()==TREE,'Expression general-type program changed')
 old=json.loads((ROOT/'docs/conformance/2026-08-support/expression-redefinition-pilot-controls.json').read_text())
 require(sorted(d['bindings'])==sorted(old['bindings']) and len(d['bindings'])==20,'Expression bindings changed')
 for row in d['bindings'].values():
  for n in ['getRelevantFeatures','getGeneralTypes']:
   require(row[n]=='org.omg.sysml.adapter.ExpressionAdapter#'+n,'Overridden expression dependency')
  for n in ['getParameterRelevantFeatures','getRelevantParameters','filterIgnoredParameters']:
   require(row[n]=='org.omg.sysml.adapter.FeatureAdapter#'+n,'Overridden parameter dependency')
 actual=[(c['kind'],c['shape'],c['position']) for c in d['controls']]
 expected={(k,s,p) for k in d['bindings'] for s in SHAPES for p in range(4)}
 require(len(actual)==960 and len(set(actual))==960 and set(actual)==expected,'Incomplete expression parameter controls')
 kinds=' | '.join(json.dumps(k) for k in sorted(d['bindings']))
 return '// Generated by tools/generate_expression_parameters.py; traversal and canonical contexts are handwritten.\n'+f'pub(super) fn supports(kind: &str, transition_guard: bool) -> bool {{ !transition_guard && matches!(kind, {kinds}) }}\n'
def main():
 p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args();s=generate(json.loads(INPUT.read_text()))
 if a.check:require(OUTPUT.read_text()==s,'Stale expression parameters')
 else:OUTPUT.write_text(s,encoding='utf-8',newline='\n')
 print('20 non-guard expression parameter bindings; 960 independent controls')
if __name__=='__main__':main()
