"""Bounded generation from resolved Multiplicity selector trees; ownership remains native handwritten Rust."""
import argparse,hashlib,json
from pathlib import Path
from generate_expression_redefinitions import canonical,require
ROOT=Path(__file__).resolve().parents[1]
INPUT=ROOT/'docs/conformance/2026-08-support/multiplicity-defaults-pilot-controls.json'
OUTPUT=ROOT/'crates/mercurio-sysml/src/language_frontend/lowering/emit/multiplicity_defaults_generated.rs'
CONTRACT='957a7455bccd82f95fe5bb4451a14b9e6539a821209b8846727bba8861dfc288'
def generate(data):
 methods=data['methods'];shape=json.dumps(canonical(methods),sort_keys=True,separators=(',',':')).encode()
 require(hashlib.sha256(shape).hexdigest()==CONTRACT,'Resolved Multiplicity selector changed; review required')
 require(set(data['bindings'])=={'Multiplicity','MultiplicityRange'},'Changed Multiplicity binding inventory')
 keys={(k,c,m) for k in data['bindings'] for c in ['detached','Package','Classifier','Class','Feature'] for m in ['OwningMembership','FeatureMembership']}
 observed=[(r['kind'],r['context'],r['membership']) for r in data['controls']]
 require(len(observed)==20 and set(observed)==keys,'Incomplete Multiplicity context matrix')
 require(all(r['relevant_count']==0 for r in data['controls']),'Changed relevant-feature policy')
 branch=methods['org.omg.sysml.adapter.MultiplicityAdapter#getDefaultSupertype']['statements'][1]['expression']
 first=branch['condition']['test_type'].rsplit('.',1)[-1];second=branch['false']['condition']['test_type'].rsplit('.',1)[-1]
 categories=[n['arguments'][0]['value'] for n in [branch['true'],branch['false']['true'],branch['false']['false']]]
 require([first,second]==['Classifier','Feature'],'Changed owner predicates')
 lines=['// Generated by tools/generate_multiplicity_defaults.py; ownership algorithm remains handwritten.',f'pub(super) const OWNER_CLASSIFIER: &str = "{first}";',f'pub(super) const OWNER_FEATURE: &str = "{second}";','pub(super) fn supports(kind:&str)->bool {matches!(kind,"Multiplicity"|"MultiplicityRange")}',"pub(super) fn default_name(kind:&str,classifier:bool,feature:bool)->Option<&'static str> {",'    Some(match kind {']
 for kind,names in sorted(data['bindings'].items()):
  require(set(names)==set(categories) and all(isinstance(v,str) and v for v in names.values()),'Missing implicit names')
  lines.append('        '+json.dumps(kind)+' => if classifier {'+json.dumps(names[categories[0]])+'} else if feature {'+json.dumps(names[categories[1]])+'} else {'+json.dumps(names[categories[2]])+'},')
 lines+=['        _ => return None,','    })','}']
 return '\n'.join(lines)+'\n'
def main():
 p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args();text=generate(json.loads(INPUT.read_text(encoding='utf-8')))
 if args.check:require(OUTPUT.read_text(encoding='utf-8')==text,'Stale Multiplicity selector')
 else:OUTPUT.write_text(text,encoding='utf-8')
 print('Multiplicity selector: two bindings / twenty controls; canonical ownership handwritten')
if __name__=='__main__':main()
