"""Generate bounded parameter predicates from resolved pinned Pilot definitions.
Traversal, ownership, effective-feature ordering and result recursion remain
explicit handwritten Rust dependencies; this is not a Java compiler.
"""
import argparse, hashlib, json
from pathlib import Path
from generate_expression_redefinitions import canonical, require
ROOT=Path(__file__).resolve().parents[1]
INPUT=ROOT/'docs/conformance/2026-08-support/mixed-parameter-pilot-controls.json'
OUTPUT=ROOT/'crates/mercurio-sysml/src/language_frontend/lowering/emit/parameter_collections_generated.rs'
BINDINGS=['AllocationUsage', 'AssertConstraintUsage', 'AttributeUsage', 'BindingConnector', 'BindingConnectorAsUsage', 'ConnectionUsage', 'Connector', 'ConstraintUsage', 'EnumerationUsage', 'EventOccurrenceUsage', 'Feature', 'Flow', 'FlowEnd', 'FlowUsage', 'InterfaceUsage', 'ItemUsage', 'MetadataFeature', 'MetadataUsage', 'Multiplicity', 'MultiplicityRange', 'OccurrenceUsage', 'PartUsage', 'PortUsage', 'Step', 'Succession', 'SuccessionAsUsage', 'SuccessionFlow', 'SuccessionFlowUsage', 'Usage', 'ViewUsage']
TREE_CONTRACT='c19d713252579d0993814b82dc64837364dc12929e8fa6f6ffe5a9613e232bcd'

def validate(data):
    require(data['provenance']['pilot_commit']=='692170b71867353b8f90341e61556f49a5beb0e5','Wrong Pilot pin')
    require(data['provenance']['jar_sha256']=='4512852638fc799505fe676955e8c78fedef1f3ce44ec90b57b34c05c31e6945','Wrong Pilot jar')
    require(hashlib.sha256(json.dumps(canonical(data['methods']),sort_keys=True,separators=(',',':')).encode()).hexdigest()==TREE_CONTRACT,'Resolved parameter methods changed; review required')
    require(sorted(data['bindings'])==BINDINGS,'Changed parameter binding inventory')
    for dispatch in data['bindings'].values():
        require(all(dispatch[n]=='org.omg.sysml.adapter.FeatureAdapter#'+n for n in ['getGeneralTypes','getParameterRelevantFeatures','getRelevantParameters','filterIgnoredParameters']),'Overridden collection dependency')
    expected=set()
    for owner in ['Behavior','Function','Class','Step','Expression']:
        for general in ['Type','Classifier','Class','Behavior','Function','Predicate','Step','Expression']:
            for shape in ['direct','empty','inherited','private','protected','diamond']:
                for position in range(4 if owner in ['Function','Expression'] else 3):
                    expected.add(('Feature',owner,general,shape,position))
    for binding in set(data['bindings'])-{'Feature'}:
        for shape in ['direct','empty','inherited']:
            for position in range(4): expected.add((binding,'Function','Class',shape,position))
    actual=[(c['kind'],c['owner_kind'],c['general_kind'],c['shape'],c['position']) for c in data['controls']]
    require(len(actual)==1164 and len(set(actual))==len(actual) and set(actual)==expected,'Incomplete or duplicate parameter controls')

def generate(data):
    validate(data)
    predicate=data['methods']['org.omg.sysml.util.FeatureUtil#isParameter']['statements'][1]['expression']
    choices=predicate['left']['expression']
    kinds=[choices[side]['test_type'].split('.')[-1] for side in ['left','right']]
    return '// Generated by tools/generate_parameter_collections.py; do not edit.\n'+''.join(f'pub(super) const OWNER_{i}: &str = "{kind}";\n' for i,kind in enumerate(kinds))+'pub(super) fn is_parameter(owner_0: bool, owner_1: bool, directed: bool) -> bool {\n    (owner_0 || owner_1) && directed\n}\n'

def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');args=p.parse_args()
    result=generate(json.loads(INPUT.read_text(encoding='utf-8')))
    if args.check: require(OUTPUT.read_text(encoding='utf-8')==result,'Stale parameter collections')
    else: OUTPUT.write_text(result,encoding='utf-8',newline='\n')
    print('Parameter predicates current: 30 bindings, 1164 controls')
if __name__=='__main__': main()
