"""Bounded resolved Action/Transition default contribution translation.
Membership, canonical typing and source projection are handwritten dependencies.
"""
import argparse,json
from pathlib import Path
from generate_occurrence_contributions import Translator,sha,condition,PREFIX
from generate_expression_redefinitions import canonical,require
ROOT=Path(__file__).resolve().parents[1]
INPUT=ROOT/'docs/conformance/2026-08-support/action-contribution-pilot-controls.json'
OUTPUT=ROOT/'crates/mercurio-sysml/src/language_frontend/lowering/emit/action_contributions_generated.rs'
TREE='b34403dff907af778ea00286d0d83ff486ddfad7c1d13a65eef59bb418a99a96'
BINDINGS='3bd724765aaae73e32d5714b6895008c8b698378a65b19153ca4dc8122e5a0c5'
CONTEXTS=('detached','Package','Class','Structure','Behavior','Step','ActionDefinition','ActionUsage','StateDefinition','StateUsage','PartDefinition','PartUsage','Feature_class','Feature_structure')
class ActionTranslator(Translator):
 def expression(self,n,locals=None,stack=()):
  env={} if locals is None else locals;k=n['kind']
  if k=='NULL_LITERAL':return '""'
  if k=='NOT_EQUAL_TO':return '('+self.expression(n['left'],env,stack)+' != '+self.expression(n['right'],env,stack)+')'
  if k=='CONDITIONAL_EXPRESSION':return '(if '+condition(self.expression(n['condition'],env,stack))+' { '+self.expression(n['true'],env,stack)+' } else { '+self.expression(n['false'],env,stack)+' })'
  if k=='INSTANCE_OF' and self.expression(n['expression'],env,stack)=='@source':
   require(n['test_type']=='org.omg.sysml.lang.sysml.StateUsage','Unassessed source predicate');return 'c.source_state'
  if k=='METHOD_INVOCATION':
   name=n['symbol'].split('#')[-1]
   if name=='getSource':return '@source'
   if name=='isEntryExitAction':return 'c.entry_exit'
   if name in ('isActionOwnedComposite','isPartOwnedComposite','isStructureOwnedComposite','isBehaviorOwnedComposite','isBehaviorOwned','isPerformanceFeature','getSubactionType','isStateTransition','isActionTransition'):
    key=n['symbol'] if n.get('receiver',{}).get('name')=='super' else self.binding['dispatch'].get(name,n['symbol'])
    require(key not in stack,'Cyclic Action translation');return self.return_expression(self.methods[key],(*stack,key))
  return super().expression(n,env,stack)
def generate(data):
 require(data['schema']=='dev.mercurio.action-contribution-controls.v1','Changed Action contribution schema')
 require(sha(canonical(data['methods']))==TREE,'Resolved Action contribution programs changed; review required')
 require(sha(data['bindings'])==BINDINGS,'Changed resolved Action contribution bindings')
 require(set(data['bindings'])=={'ActionUsage','TransitionUsage'},'Changed admitted adapters')
 declared=data['owned_member_controls']
 require(len(declared)==8 and {(r['kind'],r['child_kind']) for r in declared}=={(k,c) for k in data['bindings'] for c in ('Class','DataType','ReferenceUsage','FeatureReferenceExpression')},'Incomplete nested declaration matrix')
 for row in declared:require(row['generals']==[{'kind':'Subsetting','target':data['bindings'][row['kind']]['names']['base']}],'Nested declaration changes default contributions')
 matrix={(k,c,b,m,p,s) for k in data['bindings'] for c in CONTEXTS for b in (False,True) for m in range(8) for p in ('none','snapshot','timeslice') for s in (('none','Feature','StateUsage') if k=='TransitionUsage' else ('none',))}
 controls=data['controls']
 require(len(controls)==2688 and {(c['kind'],c['context'],c['composite'],c['typing_mask'],c['portion'],c['source_kind']) for c in controls}==matrix,'Incomplete Action contribution matrix')
 for c in controls:
  require(all(r['kind']=='Subsetting' and r['target'] in data['bindings'][c['kind']]['names'].values() for r in c['generals']),'Unresolved contribution observation')
 lines=['// Generated by resolved Action/Transition predicate/effect translation.', '// Canonical typing/membership/source inputs and full lifecycle admission are handwritten dependencies.',
 "pub(super) struct Inputs<'a> {pub composite:bool,pub structure:bool,pub data:bool,pub owner_kind:&'a str,pub owner_class:bool,pub owner_structure:bool,pub portion:&'a str,pub source_state:bool,pub entry_exit:bool}",
 "impl Inputs<'_> {fn owner_is(&self,kind:&str)->bool {super::metaclass_conforms(self.owner_kind,kind)}}",
 'pub(super) fn supports(kind:&str)->bool {matches!(kind,"ActionUsage"|"TransitionUsage")}',
 "#[allow(unused_parens)]\npub(super) fn names(kind:&str,c:&Inputs<'_>)->Option<Vec<&'static str>> {let mut roles=Vec::new();match kind {"]
 for kind,b in sorted(data['bindings'].items()):
  lines.append(json.dumps(kind)+' => {');lines.extend(ActionTranslator(data,b).effects(b['dispatch']['addDefaultGeneralType']));lines.append('},')
 lines+=['_=>return None,}','let mut result=Vec::new();for role in roles {let name=match (kind,role) {']
 for kind,b in sorted(data['bindings'].items()):
  for role,name in sorted(b['names'].items()):
   if name is not None:lines.append('('+json.dumps(kind)+','+json.dumps(role)+')=>'+json.dumps(name)+',')
 lines+=['_=>return None,};if !result.contains(&name) {result.push(name);}}Some(result)}','']
 return '\n'.join(lines)
def main():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');a=p.parse_args();code=generate(json.loads(INPUT.read_text(encoding='utf-8')))
 if a.check:require(OUTPUT.read_text(encoding='utf-8')==code,'Stale generated Action contributions')
 else:OUTPUT.write_text(code,encoding='utf-8',newline='\n')
 print('Two resolved Action contribution chains; 2688 independent controls; native generation checked')
if __name__=='__main__':main()
