"""Generate conditional expression default ordering from resolved Pilot trees."""
import argparse, hashlib, json
from pathlib import Path
from generate_expression_redefinitions import canonical, require
ROOT=Path(__file__).resolve().parents[1]
INPUT=ROOT/'docs/conformance/2026-08-support/expression-context-pilot-controls.json'
OUTPUT=ROOT/'crates/mercurio-sysml/src/language_frontend/lowering/emit/expression_context_defaults_generated.rs'
TREE_CONTRACT='db9520bfbef6a94ad121e991e13bd3125eb7d5d8e09275286d4c4c2be4701ca7'

def generate(data):
    methods=data['methods']
    shape=json.dumps(canonical(methods),sort_keys=True,separators=(',',':')).encode()
    require(hashlib.sha256(shape).hexdigest()==TREE_CONTRACT,'Resolved expression default/predicate tree changed; review required')
    bindings=data['bindings']
    require(len(bindings)==13,'Default provider inventory changed')
    expected={(k,c,b,n) for k in bindings for c in ['Class','Structure','Behavior','Step','Feature_empty','Feature_structure','Feature_behavior'] for b in [False,True] for n in ([False,True] if k=='Invariant' else [False])}
    cases=data['controls']
    observed=[(r['kind'],r['context'],r['composite'],r['negated']) for r in cases]
    require(len(observed)==196 and set(observed)==expected,'Incomplete or duplicate default context matrix')
    statements=methods['org.omg.sysml.adapter.ExpressionAdapter#addDefaultGeneralType']['statements']
    predicates={'org.omg.sysml.adapter.FeatureAdapter#isStructureOwnedComposite':'structure_owned && composite','org.omg.sysml.adapter.FeatureAdapter#isBehaviorOwnedComposite':'behavior_owned && composite','org.omg.sysml.adapter.FeatureAdapter#isBehaviorOwned':'behavior_owned'}
    output=['// Generated by tools/generate_expression_context_defaults.py; do not edit.','pub(super) fn names(kind: &str, base: &\'static str, composite: bool, structure_owned: bool, behavior_owned: bool) -> Option<Vec<&\'static str>> {','    let mut names = vec![base];','    match kind {']
    for kind,mapping in sorted(bindings.items()):
        output.append('        '+json.dumps(kind)+' => {')
        for statement in statements[1:]:
            condition=predicates[statement['condition']['expression']['symbol']]
            category=statement['then']['statements'][0]['expression']['arguments'][0]['value']
            output.append('            if '+condition+' { names.push('+json.dumps(mapping[category])+'); }')
        output.append('        },')
    output+=['        _ => return None,','    }','    Some(names)','}']
    return '\n'.join(output)+'\n'

def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    result=generate(json.loads(INPUT.read_text(encoding='utf-8')))
    if args.check: require(OUTPUT.read_text(encoding='utf-8')==result,'Generated expression context defaults stale')
    else: OUTPUT.write_text(result,encoding='utf-8',newline='\n')
    print('Expression conditional default program current: 13 providers, 196 controls')
if __name__=='__main__': main()
