"""Generate the bounded native ownership contract from resolved EMF metadata."""
import argparse
import hashlib
import json
from pathlib import Path
from export_pilot_ecore_effective import PROFILE, ROOT, cross_check
from export_pilot_grammar_structure import validate_structure

INPUT = PROFILE / 'ecore-effective.extract.json'
OUTPUT = ROOT / 'crates/mercurio-sysml/src/language_frontend/lowering/emit/ecore_ownership_generated.rs'
URI = 'https://www.omg.org/spec/SysML/20250201#//'
# Explicit KIR field bindings. No inferred casing or delegate translation.
BINDINGS = [('OWNED_RELATIONSHIPS', 'Element/ownedRelationship', 'owned_relationship', 'owning_related_element'),
            ('OWNED_ELEMENTS', 'Relationship/ownedRelatedElement', 'owned_related_element', 'owning_relationship')]


def generate(doc, grammar):
    validate_structure(grammar)
    features = {f['id']: f for f in doc['features']}
    if len(features) != len(doc['features']):
        raise ValueError('Duplicate feature identities')
    rows = []
    for constant, path, field, inverse_field in BINDINGS:
        f = features[URI + path]
        inverse = features.get(f['opposite'])
        if inverse is None or inverse['opposite'] != f['id']:
            raise ValueError('Nonreciprocal ownership opposite: ' + f['id'])
        for entry, expected in [(f, {'kind': 'reference', 'containment': True, 'container': False,
                                     'lower_bound': 0, 'upper_bound': -1, 'ordered': True, 'unique': True}),
                                (inverse, {'kind': 'reference', 'containment': False, 'container': True,
                                           'lower_bound': 0, 'upper_bound': 1, 'unique': True})]:
            for flag in ['derived', 'transient', 'volatile', 'unsettable']:
                expected[flag] = False
            expected['changeable'] = True
            for key, value in expected.items():
                if entry[key] != value:
                    raise ValueError(f'Unsupported ownership contract {entry["id"]}: {key}')
        if f['owner'] != inverse['type'] or f['type'] != inverse['owner']:
            raise ValueError('Opposite endpoint types differ')
        # The inverse KIR binding is explicit, so a changed opposite requires review.
        expected_inverse = 'Relationship/owningRelatedElement' if constant == 'OWNED_RELATIONSHIPS' else 'Element/owningRelationship'
        if inverse['id'] != URI + expected_inverse:
            raise ValueError('Unbound inverse feature')
        def short(value):
            if not value.startswith(URI):
                raise ValueError('Unexpected model namespace')
            return value[len(URI):]
        rows.append(f'pub(super) const {constant}: OwnershipContract = OwnershipContract {{\n'
                    f'    owner_kind: "{short(f["owner"])}", child_kind: "{short(f["type"])}",\n'
                    f'    field: "{field}", inverse: "{inverse_field}",\n'
                    '};\n')
    rule_id = 'org.omg.sysml.xtext.SysML::RequirementVerificationUsage'
    rule = next(r for g in grammar['grammars'] for r in g['rules'] if r['id'] == rule_id)
    target = rule['fields']['type']['fields']['classifier']['$ref']
    if target not in {r['id'] for r in doc['classes']}:
        raise ValueError('Verification rule target is not a resolved model class')
    rows.append(f'pub(super) const LEGACY_VERIFY_USAGE_METACLASS: &str = "{target.removeprefix(URI)}";\n')
    digest = hashlib.sha256(json.dumps(doc, sort_keys=True).encode()).hexdigest()
    return ('// Generated by tools/generate_ecore_ownership.py; do not edit.\n'
            f'// Resolved EMF input digest: {digest}\n'
            f'// Resolved Xtext input digest: {hashlib.sha256(json.dumps(grammar, sort_keys=True).encode()).hexdigest()}\n'
            '// Only ordered unique containment lists with optional scalar opposites are admitted.\n'
            'use super::ecore_ownership::OwnershipContract;\n\n' + '\n'.join(rows)).encode()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    doc = json.loads(INPUT.read_text(encoding='utf-8'))
    cross_check(doc, json.loads((PROFILE / 'metamodel.extract.json').read_text(encoding='utf-8')))
    data = generate(doc, json.loads((PROFILE / "grammar.structure.extract.json").read_text(encoding="utf-8")))
    if args.check:
        if OUTPUT.read_bytes() != data:
            raise ValueError('Stale native Ecore ownership contract')
    else:
        OUTPUT.write_bytes(data)
    print('Native Ecore ownership contracts current (two reciprocal containment pairs)')


if __name__ == '__main__':
    main()
