"""Generate the bounded resolved Step default selector and inherited dispatch."""
import argparse,json,hashlib
from pathlib import Path
from generate_expression_redefinitions import canonical,require
ROOT=Path(__file__).resolve().parents[1]
INPUT=ROOT/'docs/conformance/2026-08-support/step-strategy-pilot-controls.json'
OUTPUT=ROOT/'crates/mercurio-sysml/src/language_frontend/lowering/emit/step_defaults_generated.rs'
TREE_CONTRACT='456bf712028a970a31c5ee626a0f713b2e028e4428fbe888ba455dfd02646d02'

def generate(data):
    require(set(data['bindings'])=={'Step'},'Step selector binding inventory changed')
    dispatch=data['bindings']['Step']['dispatch']
    for name,value in dispatch.items(): require(value=='org.omg.sysml.adapter.FeatureAdapter#'+name,'Overridden Step dependency: '+name)
    require(set(dispatch)=={'getAllTypes','getTypes','getFeatureTypes','getGeneralTypes','getRelevantFeatures','addDefaultGeneralType'},'Missing inherited dispatch')
    require(hashlib.sha256(json.dumps(canonical(data['methods']),sort_keys=True,separators=(',',':')).encode()).hexdigest()==TREE_CONTRACT,'Resolved Step selector/predicate changed; review required')
    expected={(c,b,p) for c in ['detached','Class','Structure','Behavior','Step','Feature_empty','Feature_structure'] for b in [False,True] for p in ['none','ordinary','owned','alias']}
    observed=[(r['context'],r['composite'],r['payload']) for r in data['controls']]
    require(len(observed)==56 and set(observed)==expected and all(r['kind']=='Step' for r in data['controls']),'Incomplete or duplicate Step contexts')
    require(len(data['typing_controls'])==6 and {r['shape'] for r in data['typing_controls']}=={'empty','direct','subset','cycle','diamond','implicit_default'} and all(r['kind']=='Step' for r in data['typing_controls']),'Incomplete Step typing controls')
    predicates={'org.omg.sysml.adapter.FeatureAdapter#isStructureOwnedComposite':'structure_owned && composite','org.omg.sysml.adapter.FeatureAdapter#isBehaviorOwnedComposite':'behavior_owned && composite','org.omg.sysml.adapter.FeatureAdapter#isBehaviorOwned':'behavior_owned','org.omg.sysml.adapter.StepAdapter#isIncomingTransfer':'incoming_transfer'}
    def expression(node):
        if node['kind']=='STRING_LITERAL': return json.dumps(data['bindings']['Step']['names'][node['value']])
        require(node['kind']=='CONDITIONAL_EXPRESSION','Unsupported Step selector expression')
        return 'if '+predicates[node['condition']['symbol']]+' { '+expression(node['true'])+' } else { '+expression(node['false'])+' }'
    selected=data['methods']['org.omg.sysml.adapter.StepAdapter#getDefaultSupertype']['statements'][0]['expression']['arguments'][0]
    predicate=data['methods']['org.omg.sysml.adapter.StepAdapter#isIncomingTransfer']['statements'][0]['expression']['arguments'][0]['receiver']['receiver']['type'].split('.')[-1]
    return '// Generated by tools/generate_step_defaults.py; do not edit.\n'+f'pub(super) const PAYLOAD_TYPE: &str = "{predicate}";\n'+"pub(super) fn supports(kind: &str) -> bool { kind == \"Step\" }\n"+"pub(super) fn name(composite: bool, structure_owned: bool, behavior_owned: bool, incoming_transfer: bool) -> &'static str {\n    "+expression(selected)+'\n}\n'

def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');args=p.parse_args()
    result=generate(json.loads(INPUT.read_text(encoding='utf-8')))
    if args.check: require(OUTPUT.read_text(encoding='utf-8')==result,'Stale Step defaults')
    else: OUTPUT.write_text(result,encoding='utf-8',newline='\n')
    print('Step selector current: 56 default contexts, 6 typing controls')
if __name__=='__main__':main()
