"""Generate fail-closed constructor dependencies from complete EMF observations."""
import argparse
import hashlib
import json
from generate_ecore_model import PROFILE, ROOT, snake

SOURCE = PROFILE / "required-features-pilot-controls.json"
ECORE = PROFILE / "ecore-effective.extract.json"
OUTPUT = ROOT / "crates/mercurio-sysml/src/language_frontend/lowering/ecore_required_dependencies_generated.rs"


def render(doc, ecore):
    if doc["schema_version"] != 1 or doc["provenance"]["pilot_revision"] != "692170b71867353b8f90341e61556f49a5beb0e5":
        raise ValueError("Changed required-feature schema or pin")
    classes = {c["id"]:c for c in ecore["classes"]}
    def ancestors(identity):
        result, pending = set(), [identity]
        while pending:
            current = pending.pop()
            if current in result: continue
            result.add(current)
            pending.extend(classes[current]["super_types"])
        return result
    expected = {}
    for kind in classes.values():
        if kind["abstract"] or kind["interface"]: continue
        lineage = ancestors(kind["id"])
        for feature in ecore["features"]:
            if feature["owner"] in lineage and feature["lower_bound"] > 0 and not feature["derived"] and not feature["volatile"]:
                expected[kind["name"],feature["owner"].split("#//")[-1],feature["name"]] = feature
    seen, dependencies = set(), []
    for row in doc["controls"]:
        key = row["class"],row["owner"],row["feature"]
        if key in seen: raise ValueError("Duplicate required-feature observation")
        seen.add(key)
        if key not in expected: raise ValueError("Unknown required-feature observation")
        if ("valid" in row) == ("error" in row) or ("valid" in row and type(row["valid"]) is not bool):
            raise ValueError("Invalid observation outcome")
        feature = expected[key]
        # Non-null constructor values cannot be treated as missing. Their
        # algorithms are deliberately not inferred from one fresh observation.
        no_value = feature["kind"] == "reference" or (feature["type"].endswith("#//EString") and feature["default_value"] is None)
        if no_value and (row.get("valid") or "error" in row) and row["feature"] != "elementId":
            dependencies.append((row["class"], snake(row["feature"])))
    if seen != set(expected): raise ValueError("Incomplete required-feature observations")
    lines = ["// Generated by tools/generate_required_feature_dependencies.py; do not edit.",
             "// Observed constructor dependencies, not implemented default algorithms.",
             "pub(super) const CONSTRUCTOR_DEPENDENCIES: &[(&str, &str)] = &["]
    for kind, field in sorted(dependencies): lines.append(f'    ("{kind}", "{field}"),')
    lines.extend(["];", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    raw = SOURCE.read_bytes(); ecore_raw = ECORE.read_bytes(); doc = json.loads(raw)
    if hashlib.sha256(ecore_raw).hexdigest() != doc["provenance"]["ecore_sha256"]:
        raise ValueError("Stale Ecore provenance")
    output = "// Input SHA256: "+hashlib.sha256(raw).hexdigest()+"\n"+render(doc,json.loads(ecore_raw))
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != output: raise ValueError("Stale constructor dependencies")
    else: OUTPUT.write_text(output,encoding="utf-8",newline="\n")
    print("Required-feature dependency inventory current; native algorithm qualification is separate")

if __name__ == "__main__": main()
