"""Emit bounded producer constants from resolved pinned adapter definitions."""
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
INPUT=ROOT/'docs/conformance/2026-08-support/feature-chain-members-pilot-controls.json'
OUTPUT=ROOT/'crates/mercurio-sysml/src/language_frontend/lowering/emit/feature_chain_members_generated.rs'
EXPECTED={'org.omg.sysml.adapter.FeatureChainExpressionAdapter#addAdditionalMembers/0': 'ce9fdb438c6730f74c823bd5f70f92a81fc9fba10cfcbe022d3063fc6955aa54', 'org.omg.sysml.adapter.InvocationExpressionAdapter#addAdditionalMembers/0': 'cb5b2ed9bae7921cc11a67f3e2d4bd292368779676658b869838b286f396b9ec', 'org.omg.sysml.delegate.setting.Type_ownedFeature_SettingDelegate#basicGet/1': '471bd77ea58907d1f4027486c46f4a0730b02d0605fa95fdc869288d02ffca48', 'org.omg.sysml.util.TypeUtil#addOwnedFeatureTo/2': '04cafdeffb36b9537105b3b3863d857ab1204245b56462bfc23775c2a01159b2', 'org.omg.sysml.util.TypeUtil#addResultParameterTo/1': '1f4a6f031c1362f9574db88b0e206b20ec57b01f6828828ec579638ccce27e9f', 'org.omg.sysml.util.TypeUtil#addResultParameterTo/2': 'aca43bd39589180ee5e1a6ce79e8806b809845a35fe0c175af7c165421db075a', 'org.omg.sysml.util.TypeUtil#getOwnedParameterOf/3': 'fb761b0d8a31897afda25ee37a911e54dd9d16749176d39fe2c0905ffa091c2b', 'org.omg.sysml.util.TypeUtil#getOwnedParametersOf/1': '5fe94e7be6d741dc0c18d62219547e630eda06a1b1d2ca58a2825a2eff85c32c'}
def generate(data):
 if data.get('schema')!='dev.mercurio.feature-chain-members-controls.v1':raise ValueError('Wrong member producer schema')
 actual={k:hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':')).encode()).hexdigest() for k,v in data['methods'].items()}
 if actual!=EXPECTED:raise ValueError('Unassessed additional-member semantics')
 if data.get('bindings')!={'FeatureChainExpression':'FeatureChainExpression->org.omg.sysml.adapter.FeatureChainExpressionAdapter#addAdditionalMembers'}:raise ValueError('Unassessed producer override')
 def walk(n):
  yield n
  for c in n.get('children',[]):yield from walk(c)
 nodes=list(walk(data['methods']['org.omg.sysml.adapter.FeatureChainExpressionAdapter#addAdditionalMembers/0']))
 positions=[int(n['source']) for n in nodes if n['kind']=='INT_LITERAL']
 names=[json.loads(n['source']) for n in nodes if n['kind']=='STRING_LITERAL']
 if positions!=[0] or names!=['']:raise ValueError('Changed parameter selection or source-target naming')
 sha=hashlib.sha256(json.dumps(data['methods'],sort_keys=True,separators=(',',':')).encode()).hexdigest()
 return '// Generated by tools/generate_feature_chain_members.py; do not edit.\n'+f'pub(super) const DEFINITION_SHA:&str="{sha}";\n'+f'pub(super) const SOURCE_POSITION:usize={positions[0]};\n'+f'pub(super) const SOURCE_NAME:&str={json.dumps(names[0])};\n'+'pub(super) fn supports(kind:&str)->bool {kind.rsplit("::").next()==Some("FeatureChainExpression")}\n'
def main():
 p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args();text=generate(json.loads(INPUT.read_text(encoding='utf-8')))
 if args.check:
  if OUTPUT.read_text(encoding='utf-8')!=text:raise ValueError('Stale producer constants')
 else:OUTPUT.write_text(text,encoding='utf-8',newline='\n')
if __name__=='__main__':main()
