"""Generate bounded native dispatch from upstream-selected name delegates."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "crates/mercurio-sysml/resources/metamodels/sysml-2.0-pilot-2026-08/name-delegate-dispatch.extract.json"
OUTPUT = ROOT / "crates/mercurio-sysml/src/language_frontend/lowering/emit/name_dispatch_generated.rs"
PREFIX = "org.omg.sysml.delegate.invocation."
ALGORITHMS = {
    PREFIX+"Element_effectiveName_InvocationDelegate": ("effectiveName", "Declared"),
    PREFIX+"Element_effectiveShortName_InvocationDelegate": ("effectiveShortName", "Declared"),
    PREFIX+"Feature_effectiveName_InvocationDelegate": ("effectiveName", "Feature"),
    PREFIX+"Feature_effectiveShortName_InvocationDelegate": ("effectiveShortName", "Feature"),
    PREFIX+"ConjugatedPortDefinition_effectiveName_InvocationDelegate": ("effectiveName", "ConjugatedPort"),
}

def render(doc):
    if doc["schema"] != "dev.mercurio.name-delegate-dispatch.v1" or doc["provenance"]["pilot_revision"] != "692170b71867353b8f90341e61556f49a5beb0e5":
        raise ValueError("Changed dispatch schema or pin")
    if len(doc["classes"]) != len(set(doc["classes"])):
        raise ValueError("Duplicate class identity")
    expected = {(kind, operation) for kind in doc["classes"] for operation in ("effectiveName", "effectiveShortName")}
    bindings = {}
    for row in doc["dispatch"]:
        key = (row["class"], row["operation"])
        if key in bindings: raise ValueError("Duplicate name binding")
        algorithm = ALGORITHMS.get(row["delegate"])
        if algorithm is None or algorithm[0] != row["operation"]:
            raise ValueError("Unassessed effective-name delegate")
        path = "org.omg.sysml.logic/src/main/java/"+row["delegate"].replace(".","/")+".java"
        if path not in doc["provenance"]["source_sha256"]:
            raise ValueError("Missing selected delegate provenance")
        bindings[key] = algorithm[1]
    if set(bindings) != expected: raise ValueError("Incomplete effective-name dispatch")
    lines = ["// Generated by tools/generate_name_dispatch.py; do not edit.",
             "// Dispatch selection is imported; algorithms and qualification are separate.",
             "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
             "pub(super) enum Algorithm { Declared, Feature, ConjugatedPort }",
             "pub(super) fn algorithms(kind: &str) -> Option<[Algorithm; 2]> {",
             "    use Algorithm::*;", "    Some(match kind {"]
    for kind in sorted(doc["classes"]):
        lines.append('        "'+kind+'" => ['+bindings[kind,"effectiveName"]+", "+bindings[kind,"effectiveShortName"]+"],")
    lines.extend(["        _ => return None,", "    })", "}", ""])
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    raw = SOURCE.read_bytes()
    doc = json.loads(raw)
    effective = (SOURCE.parent / "ecore-effective.extract.json").read_bytes()
    if hashlib.sha256(effective).hexdigest() != doc["provenance"]["ecore_effective_sha256"]:
        raise ValueError("Stale resolved Ecore provenance")
    if set(doc["classes"]) != {row["name"] for row in json.loads(effective)["classes"]}:
        raise ValueError("Incomplete resolved Ecore class inventory")
    output = "// Input SHA256: "+hashlib.sha256(raw).hexdigest()+"\n"+render(doc)
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != output: raise ValueError("Stale native name dispatch")
    else: OUTPUT.write_text(output, encoding="utf-8", newline="\n")
    print("Native name dispatch current; unresolved algorithm dependencies remain explicit")

if __name__ == "__main__": main()
