"""Generate native default literals from the pinned effective Ecore model."""
import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / 'crates/mercurio-sysml/resources/metamodels/sysml-2.0-pilot-2026-08/ecore-effective.extract.json'
OUTPUT = ROOT / 'crates/mercurio-sysml/src/language_frontend/lowering/ecore_defaults_generated.rs'
EVIDENCE = ROOT / 'docs/conformance/2026-08-support/ecore-defaults-constructor-evidence.json'
URI = 'https://www.omg.org/spec/SysML/20250201#//'


def generate(doc, evidence):
    classes = {row['id'] for row in doc['classes']}
    rows = []
    for feature in doc['features']:
        literal = feature['default_literal']
        if literal is None:
            continue
        owner = feature['owner']
        if owner not in classes or not owner.startswith(URI) or feature['kind'] != 'attribute':
            raise ValueError(f'unsupported default owner or kind: {feature["id"]}')
        if literal not in ('true', 'false', 'private', 'public'):
            raise ValueError(f'unsupported Ecore default literal: {feature["id"]}={literal}')
        if feature['default_value'] != (literal == 'true' if literal in ('true', 'false') else literal):
            raise ValueError(f'EMF default value mismatch: {feature["id"]}')
        field = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', feature['name']).lower()
        rows.append((owner.removeprefix(URI), field, literal))
    if len(rows) != len(set((owner, field) for owner, field, _ in rows)):
        raise ValueError('duplicate Ecore defaults')
    lines = [
        '// Generated by tools/generate_ecore_defaults.py; do not edit.',
        '// Resolved EMF input SHA256: ' + hashlib.sha256(json.dumps(doc, sort_keys=True).encode()).hexdigest(),
        '// Constructor dependency evidence SHA256: ' + hashlib.sha256(json.dumps(evidence, sort_keys=True).encode()).hexdigest(),
        'pub(super) const DEFAULTS: &[(&str, &str, &str)] = &[',
    ]
    lines.extend(f'    ({json.dumps(owner)}, {json.dumps(field)}, {json.dumps(literal)}),'
                 for owner, field, literal in sorted(rows))
    lines.extend(['];', '// Effective primitive defaults without explicit literals; enum constructor semantics are separate.',
                  'pub(super) const PRIMITIVE_DEFAULTS: &[(&str, &str, &str)] = &['])
    primitives = {'EBoolean': bool, 'EInt': int, 'EDouble': float}
    for feature in sorted(doc['features'], key=lambda f: f['id']):
        if feature['kind'] != 'attribute' or feature['derived'] or feature['default_literal'] is not None:
            continue
        primitive = feature['type'].removeprefix('http://www.eclipse.org/emf/2002/Ecore#//')
        if primitive not in primitives:
            continue
        value = feature['default_value']
        if type(value) is not primitives[primitive] or feature['upper_bound'] != 1:
            raise ValueError('Unsupported primitive default: ' + feature['id'])
        owner = feature['owner']
        if owner not in classes or not owner.startswith(URI):
            raise ValueError('Unknown primitive default owner: ' + feature['id'])
        field = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', feature['name']).lower()
        lines.append('    (' + ', '.join(json.dumps(v) for v in [owner.removeprefix(URI), field, json.dumps(value)]) + '),')
    lines.extend(['];', '// Constructor/delegate observations block unqualified absent-value reads.',
                  'pub(super) const DEFAULT_READ_DEPENDENCIES: &[(&str, &str)] = &['])
    known = {row['name']: row for row in doc['classes']}
    by_id = {row['id']: row for row in doc['classes']}
    def lineage(identity):
        return {identity} | {ancestor for parent in by_id[identity]['super_types'] for ancestor in lineage(parent)}
    guards = {(r['class'], r['feature']) for r in evidence['constructor_overrides']}
    failures = evidence['detached_delegate_failures']
    guards.update((kind, failures['feature']) for kind in failures['classes'])
    for kind, feature in sorted(guards):
        if kind not in known: raise ValueError('Unknown constructor dependency class: '+kind)
        if not any(f['name']==feature and f['owner'] in lineage(known[kind]['id']) and f['kind']=='attribute' for f in doc['features']):
            raise ValueError('Unknown constructor dependency attribute: '+kind+'.'+feature)
        field = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', feature).lower()
        lines.append('    ('+json.dumps(kind)+', '+json.dumps(field)+'),')
    lines.extend(['];', ''])
    return '\n'.join(lines).encode(), len(rows)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    raw = INPUT.read_bytes()
    evidence = json.loads(EVIDENCE.read_text(encoding='utf-8'))
    if evidence['ecore_sha256'] != hashlib.sha256(raw).hexdigest(): raise ValueError('Stale constructor-default evidence')
    data, count = generate(json.loads(raw), evidence)
    if args.check:
        if OUTPUT.read_bytes() != data:
            raise ValueError('stale native Ecore defaults')
    else:
        OUTPUT.write_bytes(data)
    print(f'Native Ecore defaults current: {count} explicit literals')


if __name__ == '__main__':
    main()
