"""Generate native constructor constants from javac-resolved assignments."""
import argparse
import hashlib
import json
from generate_ecore_model import PROFILE, ROOT
SOURCE = PROFILE / "constructor-constants.extract.json"
ECORE = PROFILE / "ecore-effective.extract.json"
OUTPUT = ROOT / "crates/mercurio-sysml/src/language_frontend/lowering/ecore_constructor_constants_generated.rs"
BASE = "https://www.omg.org/spec/SysML/20250201#//OperatorExpression"

def render(doc, ecore):
    if doc["schema_version"] != 1 or doc["provenance"]["pilot_revision"] != "692170b71867353b8f90341e61556f49a5beb0e5":
        raise ValueError("Changed constructor schema or pin")
    classes = {c['id']:c for c in ecore['classes']}
    def inherits(identity):
        pending,seen=[identity],set()
        while pending:
            current=pending.pop()
            if current==BASE: return True
            if current in seen: continue
            seen.add(current);pending.extend(classes[current]['super_types'])
        return False
    expected={c['name'] for c in classes.values() if c['id']!=BASE and inherits(c['id'])}
    feature=next(f for f in ecore['features'] if f['id']==BASE+'/operator')
    if feature['kind']!='attribute' or feature['derived'] or feature['volatile'] or feature['upper_bound']!=1 or feature['type']!='http://www.eclipse.org/emf/2002/Ecore#//EString':
        raise ValueError('Changed operator contract')
    seen=set();rows=[]
    for row in doc['controls']:
        kind=row['class']
        if kind in seen: raise ValueError('Duplicate constructor')
        seen.add(kind)
        if kind not in expected or row['field']!='operator' or row['writes']!=['operator','OPERATOR_EDEFAULT'] or row['constant_type']!='java.lang.String':
            raise ValueError('Unassessed constructor assignment')
        if not isinstance(row['value'],str) or row['value']!=row['observed_value']:
            raise ValueError('Constructor observation disagreement')
        source='org.omg.sysml.model/src/main/java/org/omg/sysml/lang/sysml/impl/'+kind+'Impl.java'
        if source not in doc['provenance']['source_sha256']: raise ValueError('Missing constructor provenance')
        rows.append((kind,row['field'],row['value']))
    if seen!=expected: raise ValueError('Incomplete specialized constructor inventory')
    lines=['// Generated by tools/generate_constructor_constants.py; do not edit.',
           '// javac resolves the constant assignment; superclass/delegate semantics are separate.',
           'pub(super) const VALUES: &[(&str, &str, &str)] = &[']
    for row in sorted(rows): lines.append('    ('+', '.join(json.dumps(v) for v in row)+'),')
    lines.extend(['];',''])
    return '\n'.join(lines)

def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    raw=SOURCE.read_bytes();ecore=ECORE.read_bytes();doc=json.loads(raw)
    if doc['provenance']['ecore_sha256']!=hashlib.sha256(ecore).hexdigest(): raise ValueError('Stale Ecore provenance')
    output='// Input SHA256: '+hashlib.sha256(raw).hexdigest()+'\n'+render(doc,json.loads(ecore))
    if args.check:
        if OUTPUT.read_text(encoding='utf-8')!=output: raise ValueError('Stale constructor constants')
    else: OUTPUT.write_text(output,encoding='utf-8',newline='\n')
    print('Native constant constructor assignments current')
if __name__=='__main__': main()
